In [35]:
import requests
import os
import json
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
import pandas as pd
from netCDF4 import Dataset
from IPython.display import Markdown

### Interoperability Assessment of EuroArgo HTTPS File Server

### Endpoint

In [ ]:
endpoint = "https://data-argo.ifremer.fr/"

##### Table Of Content

- [Exploring the HTTPS file server](#exploring-the-https-file-server)
- [Technical interoperability](#technical-interoperability)
    - [Conformance to protocols, content-type and content negotiation](#conformance-to-protocols-content-type-and-content-negotiation)
    - [Machine accessibility and readability of metadata](#machine-accessibility--readability-of-metadata)
- [Semantic interoperability](#semantic-interoperability)
    - [Metadata availability and content](#metadata-availability-and-content)
        1. [Text files](#text-files)
        2. [NetCDF files](#netcdf-files)
        3. [CSV files](#csv-files)
        4. [HTML files](#html-files)
    - [Controlled vocabularies and ontologies](#controlled-vocabularies-and-ontologies)
        1. [Text files](#text-files)
        2. [NetCDF files](#netcdf-files)
        3. [CSV files](#csv-files)
        4. [HTML files](#html-files)
- ([Note on granularity](#note-on-granularity))

### Exploring the HTTPS file server

*Involves navigating through the directory structure, containing various files and folders, both via a user interface (browser) and programmatically.*

In [ ]:
response = requests.get(endpoint)
soup = BeautifulSoup(response.text, 'html.parser')

# Extract hyperlinks
for link in soup.find_all('a'):
    print(link.get('href'))

?C=N;O=D
?C=M;O=A
?C=S;O=A
?C=D;O=A
ar_index_global_meta.txt
ar_index_global_meta.txt.gz
ar_index_global_prof.txt
ar_index_global_prof.txt.gz
ar_index_global_tech.txt
ar_index_global_tech.txt.gz
ar_index_global_traj.txt
ar_index_global_traj.txt.gz
ar_index_this_week_meta.txt
ar_index_this_week_prof.txt
argo_bio-profile_index.txt
argo_bio-profile_index.txt.gz
argo_bio-traj_index.txt
argo_bio-traj_index.txt.gz
argo_synthetic-profile_index.txt
argo_synthetic-profile_index.txt.gz
aux/
dac/
etc/
geo/
latest_data/
readme_before_using_the_data.txt

In [ ]:
# Exploring readme metadata 
readme = requests.get("https://data-argo.ifremer.fr/readme_before_using_the_data.txt").text
Markdown(f"\n{readme}\n")

Argo real-time data is subject to only coarse fully-automated quality control checks on a limited list of parameters such as pressure, temperature, salinity, oxygen or chlorophyll.

Argo delayed-mode procedures for checking sensor drifts and offsets in salinity rely on a statistical comparison of the float data with reference data. An adjustment is made when the float PI judges that it will improve the quality of the dataset.

Users should include the supplied error estimates in their usage of Argo delayed-mode salinity data.

For both near real-time and delayed mode data, proper and appropriate use is the responsibility of the user.

To properly acknowledge Argo data usage, please use the following sentence and place the appropriate Argo DOI afterwards as described below.
"These data were collected and made freely available by the International Argo Program and the national programs that contribute to it (http://www.argo.ucsd.edu,  http://argo.jcommops.org). The Argo Program is part of the Global Ocean Observing System."

There are two options when picking an Argo DOI:
(1) Pick the one associated with when you obtained the data from the Argo GDAC. Please refer to the ADMT's DOI page (http://www.argodatamgt.org/Access-to-data/Argo-DOI-Digital-Object-Identifier) to find the correct DOI to include in your publication or product.
or
(2) If you did not obtain the Argo data from the GDAC, but from an Argo data product or other source without a date for the Argo data attached to it, use the general one with no time associated with it:
Argo (2000). Argo float data and metadata from Global Data Assembly Centre (Argo GDAC). SEANOE. http://doi.org/10.17882/42182

Argo data management documentation is available on http://www.argodatamgt.org/Documentation

Argo data long-term repository is hosted in US-NCEI https://www.nodc.noaa.gov/argo

In [ ]:
# Exploring files and folders
indexglobal_md = requests.get("https://data-argo.ifremer.fr/ar_index_global_meta.txt").text

first_lines = "\n".join(indexglobal_md.splitlines()[:20])
Markdown(f"```\n{first_lines}\n... (truncated)\n```")

```
# Title : Metadata directory file of the Argo Global Data Assembly Center
# Description : The directory file describes all metadata files of the argo GDAC ftp site.
# Project : ARGO
# Format version : 2.0
# Date of update : 20250826002102
# FTP root number 1 : ftp://ftp.ifremer.fr/ifremer/argo/dac
# FTP root number 2 : ftp://usgodae.org/pub/outgoing/argo/dac
# GDAC node : CORIOLIS
file,profiler_type,institution,date_update
aoml/13857/13857_meta.nc,845,AO,20181011200014
aoml/13858/13858_meta.nc,845,AO,20181011200015
aoml/13859/13859_meta.nc,845,AO,20181011200025
aoml/15819/15819_meta.nc,845,AO,20181011200016
aoml/15820/15820_meta.nc,845,AO,20181011200018
aoml/15851/15851_meta.nc,845,AO,20181011200026
aoml/15852/15852_meta.nc,845,AO,20181011200028
aoml/15853/15853_meta.nc,845,AO,20181011200029
aoml/15854/15854_meta.nc,845,AO,20181011200030
aoml/15855/15855_meta.nc,845,AO,20181011200034
aoml/1900022/1900022_meta.nc,851,AO,20160519222635
... (truncated)
```

In [25]:
gz_test = requests.get("https://data-argo.ifremer.fr/ar_index_global_meta.txt.gz").text
first_lines = "\n".join(gz_test.splitlines()[:10])
Markdown(f"```\n{first_lines}\n... (truncated)\n```")

```
�B��h ar_index_global_meta.txt ��]�u=r
��Wз�����;��4��=�o�V٣��2J���gq���3�I��V'$Վ����
&��˟��?�������O��?�������������������������������������?�o����������~�o��_�����?��?��?�������������_��_����������oҏ����?�˟�����O�����_X��?�������_�����/���?�����?������/����?���p�?�������������[���kU��������X������^C�uI�d������/��?��������?��GwI�������������۟��o��_���߭
��?��v��������������_���������/��o��/����U��F��_�aU��������������V�����_������������������X���W+���1���������R
����Ձ����
������\i�+%��+�����7�y��|���
^G����_o�����
>>?���V���Wy��?W�z~��?�ߟ��o��|}^߿��9Ls%�/�&P�U������L�(�4��)�RDS1�LM�Đb�?��I
)]Q�E
)CS1
... (truncated)
```

In [34]:
folder = requests.get("https://data-argo.ifremer.fr/aux/aoml/1901608/")
soup = BeautifulSoup(folder.text, 'html.parser')

# Extract hyperlinks
for link in soup.find_all('a'):
    print(link.get('href'))

file = requests.get("https://data-argo.ifremer.fr/aux/aoml/1901608/1901608_tech_aux.html")
html_1901608_tech_aux = BeautifulSoup(file.text, 'html.parser')
pretty_html = html_1901608_tech_aux.prettify()

snippet = "\n".join(pretty_html.splitlines()[:30])

Markdown(f"```html\n{snippet}\n... (truncated)\n```")

?C=N;O=D
?C=M;O=A
?C=S;O=A
?C=D;O=A
/aux/aoml/
1901608_tech_aux.html

```html
<html>
 <head>
  <!-- Window Title -->
  <title>
   Scripps Argo AUX file
  </title>
 </head>
 <body bgcolor="#FFFFFF">
  <!-- title: -->
  <table width="900">
   <tr>
    <td align="left">
     <h2>
      SIO Argo AUX Buoyancy Pumping Time Series Data:
     </h2>
    </td>
   </tr>
  </table>
  <br clear="left"/>
  <br clear="left"/>
  <h2>
   <h2>
    Serial=  8066 WMO= 1901608
   </h2>
   <br clear="left"/>
   <h2 align="left" style="white-space:pre">
    Cycle  212                           GMT  15/ 2/2017 13:36: 1
   </h2>
   <table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
    <tr>
... (truncated)
```

In [39]:
df = pd.read_csv("https://data-argo.ifremer.fr/etc/ObjectiveAnalysisWarning/aoml/ar_scoop2_AO_20130719123526.csv", sep=",", comment="#")  
df.head()

,DAC_CODE,PLATFORM_CODE,CV_NUMBER,DATE_UPDATE,DIRECTION,WEB_URL,PARAMETER,START_IMMERSION,STOP_IMMERSION,OLD_QC,NEW_QC
0,AO,5904066,29,17/07/2013 00:00:00,A,http://www.ifremer.fr/WC2argoFloats/station?&s...,PSAL,1.2,2.0,1,4
1,AO,5904066,29,17/07/2013 00:00:00,A,http://www.ifremer.fr/WC2argoFloats/station?&s...,PSAL,6.0,12.0,1,4
2,AO,4901503,42,17/07/2013 00:00:00,A,http://www.ifremer.fr/WC2argoFloats/station?&s...,PSAL,58.0,60.0,1,4
3,AO,4901503,42,17/07/2013 00:00:00,A,http://www.ifremer.fr/WC2argoFloats/station?&s...,PSAL,65.9,86.0,1,4
4,AO,5903974,23,17/07/2013 00:00:00,A,http://www.ifremer.fr/WC2argoFloats/station?&s...,TEMP,6.2,6.2,1,4

In [47]:
url_nc_file = "https://data-argo.ifremer.fr/aux/bodc/1902115/1902115_meta_aux.nc"

filename = "1902115_meta_aux.nc"
with open(filename, "wb") as f:
    f.write(requests.get(url_nc_file).content)

nc = Dataset(filename, mode="r")
print(nc)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    title: Argo float auxiliary metadata file
    institution: BODC
    source: Argo float
    history: 2024-06-26T14:43:58Z creation; 2024-06-26T14:43:58Z last update (coriolis float real time data processing)
    references: http://www.argodatamgt.org/Documentation
    user_manual_version: 1.0
    Conventions: CF-1.6 Coriolis-Argo-Aux-1.0
    decoder_version: CODA_061e
    id: https://doi.org/10.17882/42182
    dimensions(sizes): DATE_TIME(14), STRING4096(4096), STRING1024(1024), STRING256(256), STRING128(128), STRING64(64), STRING32(32), STRING16(16), STRING8(8), STRING4(4), STRING2(2), N_FLOAT_META_DATA(1), N_STATIC_CONFIG_PARAM(1), N_LAUNCH_CONFIG_PARAM(1), N_CONFIG_PARAM(1), N_SENSOR(1), N_PARAM(1), N_MISSIONS(1)
    variables(dimensions): |S1 DATA_TYPE(STRING32), |S1 FORMAT_VERSION(STRING4), |S1 DATE_CREATION(DATE_TIME), |S1 DATE_UPDATE(DATE_TIME), |S1 PLATFORM_NUMBER(STRING8), |S1 FLOAT_SERIAL_NO(STRING32), |S1 DATA_CENTRE(STRING2), |S1 FLOAT_META_DATA_NAME(N_FLOAT_META_DATA, STRING128), |S1 FLOAT_META_DATA_VALUE(N_FLOAT_META_DATA, STRING4096), |S1 FLOAT_META_DATA_DESCRIPTION(N_FLOAT_META_DATA, STRING1024), |S1 STATIC_CONFIG_PARAMETER_NAME(N_STATIC_CONFIG_PARAM, STRING128), |S1 STATIC_CONFIG_PARAMETER_VALUE(N_STATIC_CONFIG_PARAM, STRING128), |S1 STATIC_CONFIG_PARAMETER_DESCRIPTION(N_STATIC_CONFIG_PARAM, STRING1024), |S1 LAUNCH_CONFIG_PARAMETER_NAME(N_LAUNCH_CONFIG_PARAM, STRING128), float64 LAUNCH_CONFIG_PARAMETER_VALUE(N_LAUNCH_CONFIG_PARAM), |S1 LAUNCH_CONFIG_PARAMETER_DESCRIPTION(N_LAUNCH_CONFIG_PARAM, STRING1024), |S1 CONFIG_PARAMETER_NAME(N_CONFIG_PARAM, STRING128), float64 CONFIG_PARAMETER_VALUE(N_MISSIONS, N_CONFIG_PARAM), int32 CONFIG_MISSION_NUMBER(N_MISSIONS), |S1 CONFIG_MISSION_COMMENT(N_MISSIONS, STRING256), |S1 SENSOR(N_SENSOR, STRING32), |S1 SENSOR_MAKER(N_SENSOR, STRING256), |S1 SENSOR_MODEL(N_SENSOR, STRING256), |S1 SENSOR_SERIAL_NO(N_SENSOR, STRING16), |S1 PARAMETER(N_PARAM, STRING64), |S1 PARAMETER_SENSOR(N_PARAM, STRING128), |S1 PARAMETER_UNITS(N_PARAM, STRING32), |S1 PARAMETER_ACCURACY(N_PARAM, STRING32), |S1 PARAMETER_RESOLUTION(N_PARAM, STRING32), |S1 PREDEPLOYMENT_CALIB_EQUATION(N_PARAM, STRING4096), |S1 PREDEPLOYMENT_CALIB_COEFFICIENT(N_PARAM, STRING4096), |S1 PREDEPLOYMENT_CALIB_COMMENT(N_PARAM, STRING4096)
    groups:

Findings from the exploration of the https file server: 
- There is a variety of file types, including `.txt`, `.gz`, `.nc`, `.csv`, and `.html`.
- Data is offered in different ways:
    - As a single `.gzip` index file, often accompanied by a metadata .txt file with a similar name.
    - As a collection of `.nc` files organized in various folders, with accompanying metadata and technical files appearing inconsistently.
- File accessibility and format:
    - All files are accessible via HTTPS.
    - Some file types require specific handling or parsing, making them less easily machine-readable.

- The data files seem to follow a specific organizational structure, resulting in a consistent URI pattern. However, this structure does not appear to be officially documented. Clear documentation would be very helpful, as it would allow for constructing URL templates and automating data retrieval. Currently, the exact semantics of these URI patterns are unclear or somewhat obfuscated:

```
data-argo.ifremer.fr/  
├── ar_index_global_meta.txt  
├── readme_before_using_the_data.txt  
├── ...
├── aux/  
│   └── aoml/  
│   └── bodc/  
│       └── {number?}/  
│           ├── {number?}_meta_aux.nc  
│           └── ... (possibly other auxiliary NetCDF files)  
│   └── coriolis/  
│   └── ...  
├── dac/  
│   └── aoml/  
│   └── bodc/  
│       └── {number?}/  
│           ├── {number?}_Rtraj.nc  
│           ├── {number?}_meta.nc  
│           ├── {number?}_prof.nc  
│           ├── {number?}_tech.nc  
│           └── profiles/  
                └── {code}_{number}.nc  
│   └── coriolis/  
│   └── ...  
├── etc/
│   └── ObjectiveAnalysisWarning/  
│   └── Report_ObjectiveAnalysisWarning/  
│       └── {year}/  
│           └── Anomalies_Argo_Profiles_{MonthYear}.pdf  
│   └── ...  
├── geo/  
│   └── atlantic_ocean/  
│   └── ...  
├── latest_data/  
│   └── {code}_prof_{int}.nc  
└── [potentially other top-level files or directories]
```

### Technical interoperability 

*Involves checking for the use of open protocols, use of standard MIME types and support for content negotiation; to ensure that files can be accessed, processed correctly by diverse clients.*

#### Conformance to protocols, content-type and content negotiation

In [ ]:
response = requests.get(endpoint)
server_headers = response.headers

tech_results = {
    # General protocol and status checks
    "General protocol and status checks" : 
        {
        "HTTP/HTTPS Protocol": endpoint.startswith("http"),
        "Status Code 200 OK": response.status_code == 200,
        },
    # Content negotiation
    "Content negotiation" : 
        {
        "MIME Type Present": "Content-Type" in server_headers,
        "MIME Type": server_headers.get("Content-Type"),
        "Content Negotiation Support": "Vary" in server_headers or "Accept" in server_headers,
        "Vary": server_headers.get("Vary"),                         # response may change depending on 'Accept-Encoding'
        "Accept-Ranges": server_headers.get("Accept-Ranges"),       # support partial content requests (e.g., 'bytes')
        },
    # Content negotiation related headers
    "Content negotiation related headers" : 
        { 
        "Content-Length": server_headers.get("Content-Length"),             # total size of the file, if specified
        "Content-Disposition": server_headers.get("Content-Disposition"),   # tells if file is inline or attachment
        "Content-Encoding": server_headers.get("Content-Encoding"),         # compression format (e.g., gzip)
        "Accept": server_headers.get("Accept"),                             # what media types the client accepts (rare in response)
        "Accept-Encoding": server_headers.get("Accept-Encoding"),           # what compression formats the client accepts (rare in response)
        },
    # Caching-related headers
    "Caching-related headers" : 
        {
        "Cache-Control": server_headers.get("Cache-Control"),       # caching policy (e.g., no-cache, max-age)
        "ETag": server_headers.get("ETag"),                         # version identifier for the file, useful for caching and validation
        }
}

# Output the results
tech_results

{'General protocol and status checks': {'HTTP/HTTPS Protocol': True,
  'Status Code 200 OK': True},
 'Content negotiation': {'MIME Type Present': True,
  'MIME Type': 'text/html;charset=UTF-8',
  'Content Negotiation Support': True,
  'Vary': 'Accept-Encoding',
  'Accept-Ranges': None},
 'Content negotiation related headers': {'Content-Length': '810',
  'Content-Disposition': None,
  'Content-Encoding': 'gzip',
  'Accept': None,
  'Accept-Encoding': None},
 'Caching-related headers': {'Cache-Control': None, 'ETag': None}}

#### Machine accessibility / readability of metadata

In [39]:
# for code -> see code in assessment of semantic interoperability

Findings:  
**CSV / Argo text files:**
- These files are inherently flat and human-readable, making them easy to open and inspect.
- However, automated processing is challenging because:
    - Column names are not always consistent across files.
    - Many cell values are codes or numeric identifiers (e.g., DAC_CODE, PLATFORM_CODE, OLD_QC, NEW_QC) whose meaning is not explicitly documented.
    - Some columns contain mixed data types (strings, numbers, URLs), which complicates parsing.
    - Free-form text entries and irregular formatting may require additional cleaning before analysis.
- URLs included in the files could provide extra context or references, but automated scripts must handle them separately and may fail if links are broken.

**NetCDF files:**
- These files are highly structured, with clearly defined dimensions, variables, and attributes.
- Libraries such as netCDF4 or xarray provide direct programmatic access, enabling reliable extraction of data arrays.
- Multi-dimensional variables (e.g., temperature profiles over depth and time) require careful alignment of dimensions to ensure proper interpretation.
- Overall, NetCDF files are highly machine-readable, allowing automated pipelines to work efficiently with minimal preprocessing compared to CSV or text files.

**HTML files:**
- HTML is designed for human browsing, so machine access is less straightforward.
- Programmatic extraction requires parsing the HTML structure (tables, lists, nested tags) using tools like BeautifulSoup.
- Column labels, codes, and metadata may be embedded inconsistently within free text or tables, making automated processing more difficult.
- Additional preprocessing is required to extract, clean, and normalize the data for use in downstream applications.

### Semantic interoperability

*Involves checking whether the (meta)data provided adheres to common vocabularies, standards, metadata structures, and ontologies that would make it understandable and usable across systems.*

#### Metadata availability and content

##### 1. Text files associated with index .gz files

In [11]:
r = requests.get("https://data-argo.ifremer.fr/ar_index_global_meta.txt")
indexglobal_md = r.text
first_lines = "\n".join(indexglobal_md.splitlines()[:20])
Markdown(f"```\n{first_lines}\n... (truncated)\n```")

```
# Title : Metadata directory file of the Argo Global Data Assembly Center
# Description : The directory file describes all metadata files of the argo GDAC ftp site.
# Project : ARGO
# Format version : 2.0
# Date of update : 20250826002102
# FTP root number 1 : ftp://ftp.ifremer.fr/ifremer/argo/dac
# FTP root number 2 : ftp://usgodae.org/pub/outgoing/argo/dac
# GDAC node : CORIOLIS
file,profiler_type,institution,date_update
aoml/13857/13857_meta.nc,845,AO,20181011200014
aoml/13858/13858_meta.nc,845,AO,20181011200015
aoml/13859/13859_meta.nc,845,AO,20181011200025
aoml/15819/15819_meta.nc,845,AO,20181011200016
aoml/15820/15820_meta.nc,845,AO,20181011200018
aoml/15851/15851_meta.nc,845,AO,20181011200026
aoml/15852/15852_meta.nc,845,AO,20181011200028
aoml/15853/15853_meta.nc,845,AO,20181011200029
aoml/15854/15854_meta.nc,845,AO,20181011200030
aoml/15855/15855_meta.nc,845,AO,20181011200034
aoml/1900022/1900022_meta.nc,851,AO,20160519222635
... (truncated)
```

In [12]:
r = requests.get("https://data-argo.ifremer.fr/argo_bio-profile_index.txt")
indexglobal_md = r.text
first_lines = "\n".join(indexglobal_md.splitlines()[:20])
Markdown(f"```\n{first_lines}\n... (truncated)\n```")

```
# Title : Bio-Profile directory file of the Argo Global Data Assembly Center
# Description : The directory file describes all individual bio-profile files of the argo GDAC ftp site.
# Project : ARGO
# Format version : 2.2
# Date of update : 20250826072401
# FTP root number 1 : ftp://ftp.ifremer.fr/ifremer/argo/dac
# FTP root number 2 : ftp://usgodae.org/pub/outgoing/argo/dac
# GDAC node : CORIOLIS
file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
aoml/1900722/profiles/BD1900722_001.nc,20061022021624,-40.316,73.389,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_002.nc,20061101064423,-40.390,73.528,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_003.nc,20061111101222,-40.455,73.335,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_004.nc,20061121075021,-40.134,73.080,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_005.nc,20061201183300,-39.641,73.158,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_006.nc,20061211222704,-39.417,73.492,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_007.nc,20061222052018,-39.773,73.972,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_008.nc,20070101063417,-39.975,74.238,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_009.nc,20070111121456,-39.356,75.331,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_010.nc,20070121042215,-38.507,76.029,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
aoml/1900722/profiles/BD1900722_011.nc,20070131191254,-38.372,76.520,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
... (truncated)
```

In [13]:
r = requests.get("https://data-argo.ifremer.fr/etc/ar_minmax_fs.txt")
indexglobal_md = r.text
first_lines = "\n".join(indexglobal_md.splitlines()[:20])
Markdown(f"```\n{first_lines}\n... (truncated)\n```")

```
PLATFORM_CODE	PARAMETER_NAME	START_DATE	QUALITY_CODE	COMMENT	DAC
1902508	PSAL	20240910	4	Bad profiles	AO
4902919	PSAL	20240910	3	Slight drift	AO
5906273	PSAL	20240910	3	Slight drift	AO
5906526	PSAL	20240827	3	Bad adjustement on PSAL_ADJUSTED	AO
3901685	PSAL	20240910	3	Slight drift	IF
1901843	PSAL	20240527	3	Slight drift ?	AO
1902061	PSAL	20240122	3	PSAL seems ok but PSAL_ADJUSTED has a biais, at the end PSAL and PSAL_ADJUSTED seem have a bias/drift ? 	AO
1902388	PSAL	20240710	3	Jump, ASD ?	AO
1902489	PSAL	20240511	3	Slight drift ? From beginning	AO
1902512	PSAL	20240516	3	Slight drift ?	AO
2903465	PSAL	20240803	3	Slight drift ?	AO
2903864	PSAL	20240321	3	Offset/bias from first cycles	AO
3901278	PSAL	20231010	3	Drift	AO
3901290	PSAL	20231205	3	Drift	AO
3901304	PSAL	20231005	3	Drift	AO
3901798	PSAL	20240719	3	Drift	AO
3902150	PSAL	20220921	3	Drift, PSAL QC3 but PSAL_ADJUSTED (in deep levels) seems ok	AO
4902921	PSAL	20240902	3	Bad profile, ASD ?	AO
4902929	PSAL	20240817	3	Slight drift	AO
... (truncated)
```

In [14]:
r = requests.get("https://data-argo.ifremer.fr/etc/argo_sprof_index.txt")
indexglobal_md = r.text
first_lines = "\n".join(indexglobal_md.splitlines()[:20])
Markdown(f"```\n{first_lines}\n... (truncated)\n```")

```
# Title : Sprof directory file of the Argo Global Data Assembly Center
# Description : The directory file describes all s-prof files of the argo GDAC ftp site.
# Project : ARGO
# Format version : 2.2
# Date of update : 20250826053201
# FTP root number 1 : ftp://ftp.ifremer.fr/ifremer/argo/dac
# FTP root number 2 : ftp://usgodae.org/pub/outgoing/argo/dac
# GDAC node : CORIOLIS
file,profiler_type,institution,parameters,date_update
aoml/1900722/1900722_Sprof.nc,846,AO,PRES TEMP PSAL DOXY,20220628083704
aoml/1901378/1901378_Sprof.nc,846,AO,PRES TEMP PSAL DOXY NITRATE,20241217234018
aoml/1901379/1901379_Sprof.nc,846,AO,PRES TEMP PSAL DOXY NITRATE,20241218002335
aoml/1901466/1901466_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628113143
aoml/1901467/1901467_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628122514
aoml/1901468/1901468_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628123310
aoml/1901498/1901498_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628131403
aoml/1901499/1901499_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628134448
aoml/1901501/1901501_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628143502
aoml/1901668/1901668_Sprof.nc,851,AO,PRES TEMP PSAL DOXY,20220628151841
aoml/1902303/1902303_Sprof.nc,869,AO,PRES TEMP PSAL DOXY CHLA CHLA_FLUORESCENCE BBP700 CDOM PH_IN_SITU_TOTAL NITRATE,20250716011930
... (truncated)
```

##### 2. NetCDF files

In [15]:
# function to download .nc file
def download_nc_file(url):
    os.mkdir("files_euroargo_https") if not os.path.exists("files_euroargo_https") else None
    filename = url.split("/")[-1]
    file_path = os.path.join("files_euroargo_https", filename)

    #print(f"Downloading {url} to {file_path}...")
    response = requests.get(url)
    response.raise_for_status()           # Raise an error if download failed

    with open(file_path, 'wb') as f:
        f.write(response.content)
    #print("Download complete.")


#function to print metadata from a netCDF file
def nc_metadata(file_path):
    with Dataset(file_path, 'r') as nc_file:
        print("="*60)
        print(f"Metadata for: {file_path}")
        print("="*60)

        # Global Attributes
        print("\n>>> Global Attributes:")
        for attr in nc_file.ncattrs():
            print(f"  - {attr}: {getattr(nc_file, attr)}")

        # Dimensions
        print("\n>>> Dimensions:")
        for name, dim in nc_file.dimensions.items():
            print(f"  - {name}: size = {len(dim)}")

        # Variables
        print("\n>>> Variables:")
        for name, var in nc_file.variables.items():
            dims = ", ".join(var.dimensions)
            print(f"  - {name} ({dims}) -> shape = {var.shape}")
            
        print("="*60 + "\n")

In [16]:
# Example of random profile nc file
prof_url = "https://data-argo.ifremer.fr/geo/atlantic_ocean/1997/07/19970728_prof.nc"
# Downloading file
download_nc_file(prof_url)
# Getting the  metadata
nc_metadata("files_euroargo_https/19970728_prof.nc")

============================================================
Metadata for: files_euroargo_https/19970728_prof.nc
============================================================

>>> Global Attributes:
  - title: Argo float vertical profile
  - institution: FR GDAC
  - source: Argo float
  - history: 2019-04-24T08:42:02Z creation
  - references: http://www.argodatamgt.org/Documentation
  - user_manual_version: 3.1
  - Conventions: Argo-3.1 CF-1.6
  - featureType: trajectoryProfile

>>> Dimensions:
  - DATE_TIME: size = 14
  - STRING256: size = 256
  - STRING64: size = 64
  - STRING32: size = 32
  - STRING16: size = 16
  - STRING8: size = 8
  - STRING4: size = 4
  - STRING2: size = 2
  - N_PROF: size = 1
  - N_PARAM: size = 2
  - N_LEVELS: size = 102
  - N_CALIB: size = 1
  - N_HISTORY: size = 0

>>> Variables:
  - DATA_TYPE (STRING16) -> shape = (16,)
  - FORMAT_VERSION (STRING4) -> shape = (4,)
  - HANDBOOK_VERSION (STRING4) -> shape = (4,)
  - REFERENCE_DATE_TIME (DATE_TIME) -> shape = (14,)
  - DATE_CREATION (DATE_TIME) -> shape = (14,)
  - DATE_UPDATE (DATE_TIME) -> shape = (14,)
  - PLATFORM_NUMBER (N_PROF, STRING8) -> shape = (1, 8)
  - PROJECT_NAME (N_PROF, STRING64) -> shape = (1, 64)
  - PI_NAME (N_PROF, STRING64) -> shape = (1, 64)
  - STATION_PARAMETERS (N_PROF, N_PARAM, STRING16) -> shape = (1, 2, 16)
  - CYCLE_NUMBER (N_PROF) -> shape = (1,)
  - DIRECTION (N_PROF) -> shape = (1,)
  - DATA_CENTRE (N_PROF, STRING2) -> shape = (1, 2)
  - DC_REFERENCE (N_PROF, STRING32) -> shape = (1, 32)
  - DATA_STATE_INDICATOR (N_PROF, STRING4) -> shape = (1, 4)
  - DATA_MODE (N_PROF) -> shape = (1,)
  - PLATFORM_TYPE (N_PROF, STRING32) -> shape = (1, 32)
  - FLOAT_SERIAL_NO (N_PROF, STRING32) -> shape = (1, 32)
  - FIRMWARE_VERSION (N_PROF, STRING32) -> shape = (1, 32)
  - WMO_INST_TYPE (N_PROF, STRING4) -> shape = (1, 4)
  - JULD (N_PROF) -> shape = (1,)
  - JULD_QC (N_PROF) -> shape = (1,)
  - JULD_LOCATION (N_PROF) -> shape = (1,)
  - LATITUDE (N_PROF) -> shape = (1,)
  - LONGITUDE (N_PROF) -> shape = (1,)
  - POSITION_QC (N_PROF) -> shape = (1,)
  - POSITIONING_SYSTEM (N_PROF, STRING8) -> shape = (1, 8)
  - PROFILE_PRES_QC (N_PROF) -> shape = (1,)
  - PROFILE_TEMP_QC (N_PROF) -> shape = (1,)
  - VERTICAL_SAMPLING_SCHEME (N_PROF, STRING256) -> shape = (1, 256)
  - CONFIG_MISSION_NUMBER (N_PROF) -> shape = (1,)
  - PRES (N_PROF, N_LEVELS) -> shape = (1, 102)
  - PRES_QC (N_PROF, N_LEVELS) -> shape = (1, 102)
  - PRES_ADJUSTED (N_PROF, N_LEVELS) -> shape = (1, 102)
  - PRES_ADJUSTED_QC (N_PROF, N_LEVELS) -> shape = (1, 102)
  - PRES_ADJUSTED_ERROR (N_PROF, N_LEVELS) -> shape = (1, 102)
  - TEMP (N_PROF, N_LEVELS) -> shape = (1, 102)
  - TEMP_QC (N_PROF, N_LEVELS) -> shape = (1, 102)
  - TEMP_ADJUSTED (N_PROF, N_LEVELS) -> shape = (1, 102)
  - TEMP_ADJUSTED_QC (N_PROF, N_LEVELS) -> shape = (1, 102)
  - TEMP_ADJUSTED_ERROR (N_PROF, N_LEVELS) -> shape = (1, 102)
  - PARAMETER (N_PROF, N_CALIB, N_PARAM, STRING16) -> shape = (1, 1, 2, 16)
  - SCIENTIFIC_CALIB_EQUATION (N_PROF, N_CALIB, N_PARAM, STRING256) -> shape = (1, 1, 2, 256)
  - SCIENTIFIC_CALIB_COEFFICIENT (N_PROF, N_CALIB, N_PARAM, STRING256) -> shape = (1, 1, 2, 256)
  - SCIENTIFIC_CALIB_COMMENT (N_PROF, N_CALIB, N_PARAM, STRING256) -> shape = (1, 1, 2, 256)
  - SCIENTIFIC_CALIB_DATE (N_PROF, N_CALIB, N_PARAM, DATE_TIME) -> shape = (1, 1, 2, 14)
  - HISTORY_INSTITUTION (N_HISTORY, N_PROF, STRING4) -> shape = (0, 1, 4)
  - HISTORY_STEP (N_HISTORY, N_PROF, STRING4) -> shape = (0, 1, 4)
  - HISTORY_SOFTWARE (N_HISTORY, N_PROF, STRING4) -> shape = (0, 1, 4)
  - HISTORY_SOFTWARE_RELEASE (N_HISTORY, N_PROF, STRING4) -> shape = (0, 1, 4)
  - HISTORY_REFERENCE (N_HISTORY, N_PROF, STRING64) -> shape = (0, 1, 64)
  - HISTORY_DATE (N_HISTORY, N_PROF, DATE_TIME) -> shape = (0, 1, 14)
  - HISTORY_ACTION (N_HISTORY, N_PROF, STRING4) -> shape = (0, 1, 4)
  - HISTORY_PARAMETER (N_HISTORY, N_PROF, STRING16) -> shape = (0, 1, 16)
  - HISTORY_START_PRES (N_HISTORY, N_PROF) -> shape = (0, 1)
  - HISTORY_STOP_PRES (N_HISTORY, N_PROF) -> shape = (0, 1)
  - HISTORY_PREVIOUS_VALUE (N_HISTORY, N_PROF) -> shape = (0, 1)
  - HISTORY_QCTEST (N_HISTORY, N_PROF, STRING16) -> shape = (0, 1, 16)
============================================================

In [17]:
# Example of random meta nc file
meta_url = "https://data-argo.ifremer.fr/aux/bodc/1902115/1902115_meta_aux.nc"
# Downloading file
download_nc_file(meta_url)
# Getting the metadata
nc_metadata("files_euroargo_https/1902115_meta_aux.nc")

============================================================
Metadata for: files_euroargo_https/1902115_meta_aux.nc
============================================================

>>> Global Attributes:
  - title: Argo float auxiliary metadata file
  - institution: BODC
  - source: Argo float
  - history: 2024-06-26T14:43:58Z creation; 2024-06-26T14:43:58Z last update (coriolis float real time data processing)
  - references: http://www.argodatamgt.org/Documentation
  - user_manual_version: 1.0
  - Conventions: CF-1.6 Coriolis-Argo-Aux-1.0
  - decoder_version: CODA_061e
  - id: https://doi.org/10.17882/42182

>>> Dimensions:
  - DATE_TIME: size = 14
  - STRING4096: size = 4096
  - STRING1024: size = 1024
  - STRING256: size = 256
  - STRING128: size = 128
  - STRING64: size = 64
  - STRING32: size = 32
  - STRING16: size = 16
  - STRING8: size = 8
  - STRING4: size = 4
  - STRING2: size = 2
  - N_FLOAT_META_DATA: size = 1
  - N_STATIC_CONFIG_PARAM: size = 1
  - N_LAUNCH_CONFIG_PARAM: size = 1
  - N_CONFIG_PARAM: size = 1
  - N_SENSOR: size = 1
  - N_PARAM: size = 1
  - N_MISSIONS: size = 1

>>> Variables:
  - DATA_TYPE (STRING32) -> shape = (32,)
  - FORMAT_VERSION (STRING4) -> shape = (4,)
  - DATE_CREATION (DATE_TIME) -> shape = (14,)
  - DATE_UPDATE (DATE_TIME) -> shape = (14,)
  - PLATFORM_NUMBER (STRING8) -> shape = (8,)
  - FLOAT_SERIAL_NO (STRING32) -> shape = (32,)
  - DATA_CENTRE (STRING2) -> shape = (2,)
  - FLOAT_META_DATA_NAME (N_FLOAT_META_DATA, STRING128) -> shape = (1, 128)
  - FLOAT_META_DATA_VALUE (N_FLOAT_META_DATA, STRING4096) -> shape = (1, 4096)
  - FLOAT_META_DATA_DESCRIPTION (N_FLOAT_META_DATA, STRING1024) -> shape = (1, 1024)
  - STATIC_CONFIG_PARAMETER_NAME (N_STATIC_CONFIG_PARAM, STRING128) -> shape = (1, 128)
  - STATIC_CONFIG_PARAMETER_VALUE (N_STATIC_CONFIG_PARAM, STRING128) -> shape = (1, 128)
  - STATIC_CONFIG_PARAMETER_DESCRIPTION (N_STATIC_CONFIG_PARAM, STRING1024) -> shape = (1, 1024)
  - LAUNCH_CONFIG_PARAMETER_NAME (N_LAUNCH_CONFIG_PARAM, STRING128) -> shape = (1, 128)
  - LAUNCH_CONFIG_PARAMETER_VALUE (N_LAUNCH_CONFIG_PARAM) -> shape = (1,)
  - LAUNCH_CONFIG_PARAMETER_DESCRIPTION (N_LAUNCH_CONFIG_PARAM, STRING1024) -> shape = (1, 1024)
  - CONFIG_PARAMETER_NAME (N_CONFIG_PARAM, STRING128) -> shape = (1, 128)
  - CONFIG_PARAMETER_VALUE (N_MISSIONS, N_CONFIG_PARAM) -> shape = (1, 1)
  - CONFIG_MISSION_NUMBER (N_MISSIONS) -> shape = (1,)
  - CONFIG_MISSION_COMMENT (N_MISSIONS, STRING256) -> shape = (1, 256)
  - SENSOR (N_SENSOR, STRING32) -> shape = (1, 32)
  - SENSOR_MAKER (N_SENSOR, STRING256) -> shape = (1, 256)
  - SENSOR_MODEL (N_SENSOR, STRING256) -> shape = (1, 256)
  - SENSOR_SERIAL_NO (N_SENSOR, STRING16) -> shape = (1, 16)
  - PARAMETER (N_PARAM, STRING64) -> shape = (1, 64)
  - PARAMETER_SENSOR (N_PARAM, STRING128) -> shape = (1, 128)
  - PARAMETER_UNITS (N_PARAM, STRING32) -> shape = (1, 32)
  - PARAMETER_ACCURACY (N_PARAM, STRING32) -> shape = (1, 32)
  - PARAMETER_RESOLUTION (N_PARAM, STRING32) -> shape = (1, 32)
  - PREDEPLOYMENT_CALIB_EQUATION (N_PARAM, STRING4096) -> shape = (1, 4096)
  - PREDEPLOYMENT_CALIB_COEFFICIENT (N_PARAM, STRING4096) -> shape = (1, 4096)
  - PREDEPLOYMENT_CALIB_COMMENT (N_PARAM, STRING4096) -> shape = (1, 4096)
============================================================

In [18]:
# Example of random tech nc file 
tech_url = "https://data-argo.ifremer.fr/aux/bodc/1902115/1902115_tech_aux.nc"
# Downloading file
download_nc_file(tech_url)
# Getting the metadata
nc_metadata("files_euroargo_https/1902115_tech_aux.nc")

============================================================
Metadata for: files_euroargo_https/1902115_tech_aux.nc
============================================================

>>> Global Attributes:
  - title: Argo float auxiliary technical data file
  - institution: BODC
  - source: Argo float
  - history: 2024-06-26T14:43:58Z creation; 2024-09-19T00:18:33Z last update (coriolis float real time data processing)
  - references: http://www.argodatamgt.org/Documentation
  - user_manual_version: 1.0
  - Conventions: CF-1.6 Coriolis-Argo-Aux-1.0
  - decoder_version: CODA_061e
  - id: https://doi.org/10.17882/42182

>>> Dimensions:
  - DATE_TIME: size = 14
  - STRING1024: size = 1024
  - STRING256: size = 256
  - STRING64: size = 64
  - STRING32: size = 32
  - STRING8: size = 8
  - STRING4: size = 4
  - STRING2: size = 2
  - N_TECH_AUX_LABEL: size = 113
  - N_TECH_MEAS_PARAM: size = 2
  - N_TECH_MEASUREMENT: size = 1896
  - N_TECH_PARAM: size = 1308

>>> Variables:
  - PLATFORM_NUMBER (STRING8) -> shape = (8,)
  - DATA_TYPE (STRING32) -> shape = (32,)
  - FORMAT_VERSION (STRING4) -> shape = (4,)
  - REFERENCE_DATE_TIME (DATE_TIME) -> shape = (14,)
  - TECHNICAL_MEASUREMENT_PARAMETERS (N_TECH_MEAS_PARAM, STRING64) -> shape = (2, 64)
  - DATA_CENTRE (STRING2) -> shape = (2,)
  - DATE_CREATION (DATE_TIME) -> shape = (14,)
  - DATE_UPDATE (DATE_TIME) -> shape = (14,)
  - TECHNICAL_PARAMETER_NAME (N_TECH_PARAM, STRING256) -> shape = (1308, 256)
  - TECHNICAL_PARAMETER_VALUE (N_TECH_PARAM, STRING256) -> shape = (1308, 256)
  - CYCLE_NUMBER (N_TECH_PARAM) -> shape = (1308,)
  - TECH_AUX_PARAM_LABEL (N_TECH_AUX_LABEL, STRING256) -> shape = (113, 256)
  - TECH_AUX_PARAM_DESCRIPTION (N_TECH_AUX_LABEL, STRING1024) -> shape = (113, 1024)
  - JULD (N_TECH_MEASUREMENT) -> shape = (1896,)
  - JULD_STATUS (N_TECH_MEASUREMENT) -> shape = (1896,)
  - JULD_QC (N_TECH_MEASUREMENT) -> shape = (1896,)
  - JULD_ADJUSTED (N_TECH_MEASUREMENT) -> shape = (1896,)
  - JULD_ADJUSTED_STATUS (N_TECH_MEASUREMENT) -> shape = (1896,)
  - JULD_ADJUSTED_QC (N_TECH_MEASUREMENT) -> shape = (1896,)
  - CYCLE_NUMBER_MEAS (N_TECH_MEASUREMENT) -> shape = (1896,)
  - MEASUREMENT_CODE (N_TECH_MEASUREMENT) -> shape = (1896,)
  - VALVE_ACTION_DURATION (N_TECH_MEASUREMENT) -> shape = (1896,)
  - VALVE_ACTION_DURATION_QC (N_TECH_MEASUREMENT) -> shape = (1896,)
  - PUMP_ACTION_DURATION (N_TECH_MEASUREMENT) -> shape = (1896,)
  - PUMP_ACTION_DURATION_QC (N_TECH_MEASUREMENT) -> shape = (1896,)
============================================================

##### 3. CSV files

In [51]:
csv_url = "https://data-argo.ifremer.fr/etc/ObjectiveAnalysisWarning/kordi/ar_scoop2_KO_20141107123100.csv"
df = pd.read_csv(csv_url)
df

,DAC_CODE,PLATFORM_CODE,CV_NUMBER,DATE_UPDATE,DIRECTION,WEB_URL,PARAMETER,START_IMMERSION,STOP_IMMERSION,OLD_QC,NEW_QC
0,KO,2900922,258,07/10/2014 00:00:00,A,http://www.ifremer.fr/co-argoFloats/station?st...,PSAL,86.0,86.0,1,4
1,KO,2900922,258,07/10/2014 00:00:00,A,http://www.ifremer.fr/co-argoFloats/station?st...,TEMP,48.9,48.9,1,4
2,KO,2900922,258,07/10/2014 00:00:00,A,http://www.ifremer.fr/co-argoFloats/station?st...,TEMP,86.0,86.0,1,4

##### 4. HTML files

In [52]:
# (note: URL was also assessed in browser)
html_url = "https://data-argo.ifremer.fr/aux/aoml/1901608/1901608_tech_aux.html"
html_file = requests.get(html_url)
BeautifulSoup(html_file.text, 'html.parser')

<html>
<head>
<!-- Window Title -->
<title> Scripps Argo AUX file</title>
</head>
<body bgcolor="#FFFFFF">
<!-- title: -->
<table width="900">
<tr>
<td align="left">
<h2>SIO Argo AUX Buoyancy Pumping Time Series Data:
</h2>
</td>
</tr></table>
<br clear="left"/>
<br clear="left"/>
<h2>
<h2>Serial=  8066 WMO= 1901608</h2>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  212                           GMT  15/ 2/2017 13:36: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    105.28</td>
<td align="center">        48</td>
<td align="center">     10.15</td>
<td align="center">       442</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1214.00</td>
<td align="center">       150</td>
<td align="center">      5.84</td>
<td align="center">      1828</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1160.08</td>
<td align="center">        30</td>
<td align="center">      6.25</td>
<td align="center">      1719</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1085.76</td>
<td align="center">        30</td>
<td align="center">      6.23</td>
<td align="center">      1648</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>
<td align="center">    985.32</td>
<td align="center">        30</td>
<td align="center">      6.60</td>
<td align="center">      1509</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         6</td>
<td align="center">    876.72</td>
<td align="center">        30</td>
<td align="center">      6.91</td>
<td align="center">      1381</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         7</td>
<td align="center">    745.56</td>
<td align="center">        30</td>
<td align="center">      7.43</td>
<td align="center">      1227</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         8</td>
<td align="center">    191.56</td>
<td align="center">        30</td>
<td align="center">      9.70</td>
<td align="center">       520</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         9</td>
<td align="center">     -0.00</td>
<td align="center">        30</td>
<td align="center">     10.57</td>
<td align="center">       264</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">        10</td>
<td align="center">     -0.04</td>
<td align="center">       180</td>
<td align="center">     10.53</td>
<td align="center">       267</td>
<td align="center">         7</td>
<td align="center">        11</td>
</tr>
</table>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  211                           GMT   5/ 2/2017 19: 5: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    107.24</td>
<td align="center">        47</td>
<td align="center">     10.28</td>
<td align="center">       442</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1223.88</td>
<td align="center">       150</td>
<td align="center">      6.26</td>
<td align="center">      1828</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1167.80</td>
<td align="center">        30</td>
<td align="center">      6.37</td>
<td align="center">      1751</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1074.24</td>
<td align="center">        30</td>
<td align="center">      6.66</td>
<td align="center">      1642</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>
<td align="center">    961.60</td>
<td align="center">        30</td>
<td align="center">      6.98</td>
<td align="center">      1497</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         6</td>
<td align="center">    838.04</td>
<td align="center">        30</td>
<td align="center">      7.25</td>
<td align="center">      1366</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         7</td>
<td align="center">    423.28</td>
<td align="center">        30</td>
<td align="center">      8.95</td>
<td align="center">       821</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         8</td>
<td align="center">     32.32</td>
<td align="center">        30</td>
<td align="center">     10.51</td>
<td align="center">       303</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         9</td>
<td align="center">     16.84</td>
<td align="center">        30</td>
<td align="center">     10.53</td>
<td align="center">       283</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">        10</td>
<td align="center">     -0.04</td>
<td align="center">       181</td>
<td align="center">     10.61</td>
<td align="center">       260</td>
<td align="center">         7</td>
<td align="center">        10</td>
</tr>
</table>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  210                           GMT  27/ 1/2017  0:33: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    108.52</td>
<td align="center">        46</td>
<td align="center">     10.28</td>
<td align="center">       461</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1051.32</td>
<td align="center">         1</td>
<td align="center">      7.66</td>
<td align="center">      1576</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1253.32</td>
<td align="center">       150</td>
<td align="center">      6.45</td>
<td align="center">      1887</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1176.60</td>
<td align="center">        30</td>
<td align="center">      6.73</td>
<td align="center">      1776</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>
<td align="center">   1076.36</td>
<td align="center">        30</td>
<td align="center">      6.90</td>
<td align="center">      1651</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         6</td>
<td align="center">    958.08</td>
<td align="center">        30</td>
<td align="center">      7.42</td>
<td align="center">      1480</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         7</td>
<td align="center">    692.96</td>
<td align="center">        30</td>
<td align="center">      8.33</td>
<td align="center">      1148</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         8</td>
<td align="center">    138.64</td>
<td align="center">        30</td>
<td align="center">     10.13</td>
<td align="center">       454</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         9</td>
<td align="center">      0.12</td>
<td align="center">        30</td>
<td align="center">     10.74</td>
<td align="center">       261</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">        10</td>
<td align="center">      0.04</td>
<td align="center">       180</td>
<td align="center">     10.68</td>
<td align="center">       257</td>
<td align="center">         7</td>
<td align="center">        12</td>
</tr>
</table>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  209                           GMT  17/ 1/2017  6: 4: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    104.24</td>
<td align="center">        44</td>
<td align="center">     10.41</td>
<td align="center">       442</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1089.12</td>
<td align="center">         2</td>
<td align="center">      7.03</td>
<td align="center">      1692</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1630.88</td>
<td align="center">       150</td>
<td align="center">      5.87</td>
<td align="center">      2350</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1558.24</td>
<td align="center">        30</td>
<td align="center">      6.19</td>
<td align="center">      2235</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>
<td align="center">   1472.72</td>
<td align="center">        30</td>
<td align="center">      6.28</td>
<td align="center">      2140</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         6</td>
<td align="center">   1375.12</td>
<td align="center">        30</td>
<td align="center">      6.38</td>
<td align="center">      2060</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         7</td>
<td align="center">   1261.76</td>
<td align="center">        30</td>
<td align="center">      6.88</td>
<td align="center">      1858</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         8</td>
<td align="center">   1135.96</td>
<td align="center">        30</td>
<td align="center">      7.07</td>
<td align="center">      1720</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         9</td>
<td align="center">    736.96</td>
<td align="center">        30</td>
<td align="center">      8.21</td>
<td align="center">      1235</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">        10</td>
<td align="center">    200.20</td>
<td align="center">        30</td>
<td align="center">     10.01</td>
<td align="center">       553</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">        11</td>
<td align="center">      0.12</td>
<td align="center">        30</td>
<td align="center">     10.67</td>
<td align="center">       295</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">        12</td>
<td align="center">      0.08</td>
<td align="center">       180</td>
<td align="center">     10.59</td>
<td align="center">       318</td>
<td align="center">         7</td>
<td align="center">         8</td>
</tr>
</table>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  208                           GMT  16/ 1/2017  5:21: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    108.72</td>
<td align="center">        43</td>
<td align="center">     10.54</td>
<td align="center">       442</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1109.12</td>
<td align="center">         2</td>
<td align="center">      7.41</td>
<td align="center">      1769</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1289.28</td>
<td align="center">       150</td>
<td align="center">      6.94</td>
<td align="center">      1924</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1196.16</td>
<td align="center">        30</td>
<td align="center">      7.36</td>
<td align="center">      1781</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>
<td align="center">   1071.48</td>
<td align="center">        30</td>
<td align="center">      7.51</td>
<td align="center">      1653</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         6</td>
<td align="center">    811.68</td>
<td align="center">        30</td>
<td align="center">      8.17</td>
<td align="center">      1332</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         7</td>
<td align="center">    255.12</td>
<td align="center">        30</td>
<td align="center">     10.01</td>
<td align="center">       595</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         8</td>
<td align="center">      0.24</td>
<td align="center">        30</td>
<td align="center">     10.78</td>
<td align="center">       261</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         9</td>
<td align="center">      0.20</td>
<td align="center">       180</td>
<td align="center">     10.75</td>
<td align="center">       262</td>
<td align="center">         7</td>
<td align="center">        14</td>
</tr>
</table>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  207                           GMT   6/ 1/2017 11:32: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    101.92</td>
<td align="center">        45</td>
<td align="center">     10.47</td>
<td align="center">       442</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1246.16</td>
<td align="center">       150</td>
<td align="center">      7.28</td>
<td align="center">      1870</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1140.76</td>
<td align="center">        30</td>
<td align="center">      7.56</td>
<td align="center">      1736</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1012.76</td>
<td align="center">        30</td>
<td align="center">      7.93</td>
<td align="center">      1570</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>
<td align="center">    597.48</td>
<td align="center">        30</td>
<td align="center">      9.11</td>
<td align="center">      1046</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         6</td>
<td align="center">     74.16</td>
<td align="center">        30</td>
<td align="center">     10.56</td>
<td align="center">       361</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         7</td>
<td align="center">      0.08</td>
<td align="center">        30</td>
<td align="center">     10.81</td>
<td align="center">       261</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         8</td>
<td align="center">      0.04</td>
<td align="center">       180</td>
<td align="center">     10.78</td>
<td align="center">       264</td>
<td align="center">         7</td>
<td align="center">        18</td>
</tr>
</table>
<br clear="left"/>
<h2 align="left" style="white-space:pre">Cycle  206                           GMT  27/12/2016 17:20: 1</h2>
<table align="left" border="1" cellpadding="0" cellspacing="0" width="900">
<tr>
<td align="center">Pump Count</td>
<td align="center">Pressure (db)</td>
<td align="center">Time (s)</td>
<td align="center">Voltage (V)</td>
<td align="center">Current (ma)</td>
<td align="center">Vacuum0<br/>(load-start)</td>
<td align="center">Vacuum1<br/>(load-stop)</td>
</tr>
<tr>
<td align="center">         1</td>
<td align="center">    105.40</td>
<td align="center">        44</td>
<td align="center">     10.60</td>
<td align="center">       461</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         2</td>
<td align="center">   1044.36</td>
<td align="center">         1</td>
<td align="center">      7.98</td>
<td align="center">      1692</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         3</td>
<td align="center">   1254.92</td>
<td align="center">       150</td>
<td align="center">      7.35</td>
<td align="center">      1890</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         4</td>
<td align="center">   1144.76</td>
<td align="center">        30</td>
<td align="center">      7.81</td>
<td align="center">      1731</td>
<td align="center">         7</td>
<td align="center">         7</td>
</tr>
<tr>
<td align="center">         5</td>

Findings:  

**CSV / Argo text files:**
- Metadata is present but often incomplete or not standardized.
- Many columns contain codes or numeric identifiers (e.g., DAC_CODE, PLATFORM_CODE, OLD_QC, NEW_QC) that likely reference standard terms or parameters, but their meaning is not explicitly documented and no external mapping is provided.
- Relationships between observations, parameters, or measurement cycles are often implicit, making it harder for systems to understand the full context of the data.
- Free-form descriptions or notes may vary across files, further limiting semantic consistency.

**NetCDF files:**
- Variables and attributes are generally well-documented and standardized, often following Argo conventions for variable names and units.
- Global attributes provide provenance, source information, and context, which is critical for semantic interoperability.
- Even with good standardization, full semantic interoperability requires consistent use of controlled vocabularies and external references; deviations or non-standard terms still require mapping to a common schema.
- Overall, NetCDF files provide strong support for semantic interoperability, making it easier to integrate and interpret data across datasets and systems.

**HTML files:**
- Metadata is present within tables, lists, or free-form text, but its meaning is not standardized, and key relationships may be implied rather than explicit.
- URLs and embedded links can provide additional context or references, but automated interpretation requires additional mapping and processing.
- Semantic interoperability is limited because systems cannot directly infer the meaning of codes, labels, or values without human guidance or additional metadata mapping.

#### Controlled vocabularies or Ontologies

*Involves checking for Standard metadata schemas (e.g., ISO 19115, CF conventions for NetCDF, Dublin Core) and other semantic vocabularies or ontologies*

##### 1. Text files associated with index .gz files

In [53]:
gz_metadata_url = "https://data-argo.ifremer.fr/ar_index_global_meta.txt"
metadata = requests.get(gz_metadata_url)
BeautifulSoup(metadata.text, 'html.parser')

# Title : Metadata directory file of the Argo Global Data Assembly Center
# Description : The directory file describes all metadata files of the argo GDAC ftp site.
# Project : ARGO
# Format version : 2.0
# Date of update : 20250729002101
# FTP root number 1 : ftp://ftp.ifremer.fr/ifremer/argo/dac
# FTP root number 2 : ftp://usgodae.org/pub/outgoing/argo/dac
# GDAC node : CORIOLIS
file,profiler_type,institution,date_update
aoml/13857/13857_meta.nc,845,AO,20181011200014
aoml/13858/13858_meta.nc,845,AO,20181011200015
aoml/13859/13859_meta.nc,845,AO,20181011200025
aoml/15819/15819_meta.nc,845,AO,20181011200016
aoml/15820/15820_meta.nc,845,AO,20181011200018
aoml/15851/15851_meta.nc,845,AO,20181011200026
aoml/15852/15852_meta.nc,845,AO,20181011200028
aoml/15853/15853_meta.nc,845,AO,20181011200029
aoml/15854/15854_meta.nc,845,AO,20181011200030
aoml/15855/15855_meta.nc,845,AO,20181011200034
aoml/1900022/1900022_meta.nc,851,AO,20160519222635
aoml/1900033/1900033_meta.nc,851,AO,20160519222621
aoml/1900034/1900034_meta.nc,851,AO,20160519222621
aoml/1900035/1900035_meta.nc,851,AO,20160519222622
aoml/1900036/1900036_meta.nc,851,AO,20160519222629
aoml/1900037/1900037_meta.nc,851,AO,20160519222625
aoml/1900038/1900038_meta.nc,851,AO,20160519222625
aoml/1900039/1900039_meta.nc,851,AO,20160519222627
aoml/1900040/1900040_meta.nc,851,AO,20160519222628
aoml/1900041/1900041_meta.nc,851,AO,20160519222639
aoml/1900042/1900042_meta.nc,846,AO,20160527003521
aoml/1900043/1900043_meta.nc,846,AO,20160527003525
aoml/1900044/1900044_meta.nc,846,AO,20160527003542
aoml/1900045/1900045_meta.nc,846,AO,20160527003537
aoml/1900046/1900046_meta.nc,846,AO,20181012200117
aoml/1900047/1900047_meta.nc,846,AO,20160527003510
aoml/1900048/1900048_meta.nc,846,AO,20160527003518
aoml/1900049/1900049_meta.nc,846,AO,20160527003516
aoml/1900050/1900050_meta.nc,846,AO,20210428200444
aoml/1900051/1900051_meta.nc,846,AO,20160527003329
aoml/1900052/1900052_meta.nc,846,AO,20210428200449
aoml/1900053/1900053_meta.nc,846,AO,20181012200039
aoml/1900054/1900054_meta.nc,846,AO,20181012200033
aoml/1900055/1900055_meta.nc,846,AO,20160527003438
aoml/1900056/1900056_meta.nc,846,AO,20210428200517
aoml/1900057/1900057_meta.nc,851,AO,20160519222635
aoml/1900058/1900058_meta.nc,851,AO,20160519222808
aoml/1900059/1900059_meta.nc,851,AO,20160519222638
aoml/1900060/1900060_meta.nc,851,AO,20210428200529
aoml/1900061/1900061_meta.nc,851,AO,20160519222809
aoml/1900062/1900062_meta.nc,851,AO,20160519222810
aoml/1900143/1900143_meta.nc,846,AO,20210428200456
aoml/1900144/1900144_meta.nc,846,AO,20160527003404
aoml/1900145/1900145_meta.nc,846,AO,20160527003547
aoml/1900146/1900146_meta.nc,846,AO,20160527003528
aoml/1900147/1900147_meta.nc,846,AO,20160527003532
aoml/1900148/1900148_meta.nc,846,AO,20160527003547
aoml/1900149/1900149_meta.nc,846,AO,20160527003643
aoml/1900150/1900150_meta.nc,846,AO,20160527003650
aoml/1900151/1900151_meta.nc,846,AO,20160527003656
aoml/1900152/1900152_meta.nc,846,AO,20160527003504
aoml/1900153/1900153_meta.nc,846,AO,20160527003639
aoml/1900154/1900154_meta.nc,846,AO,20210428200558
aoml/1900155/1900155_meta.nc,846,AO,20160527003946
aoml/1900156/1900156_meta.nc,846,AO,20160527003952
aoml/1900157/1900157_meta.nc,846,AO,20160527004001
aoml/1900158/1900158_meta.nc,846,AO,20160527004037
aoml/1900159/1900159_meta.nc,846,AO,20160527004039
aoml/1900160/1900160_meta.nc,846,AO,20160527004135
aoml/1900161/1900161_meta.nc,846,AO,20160527004137
aoml/1900162/1900162_meta.nc,846,AO,20160527004139
aoml/1900163/1900163_meta.nc,851,AO,20160519222822
aoml/1900164/1900164_meta.nc,851,AO,20160519222823
aoml/1900165/1900165_meta.nc,851,AO,20160519222824
aoml/1900166/1900166_meta.nc,851,AO,20160519222825
aoml/1900167/1900167_meta.nc,852,AO,20190226210012
aoml/1900168/1900168_meta.nc,852,AO,20190226210012
aoml/1900169/1900169_meta.nc,846,AO,20181012200222
aoml/1900170/1900170_meta.nc,846,AO,20160527004145
aoml/1900171/1900171_meta.nc,846,AO,20160527004151
aoml/1900172/1900172_meta.nc,846,AO,20160527004152
aoml/1900180/1900180_meta.nc,846,AO,20181012200225
aoml/1900181/1900181_meta.nc,846,AO,20210428200613
aoml/1900182/1900182_meta.nc,846,AO,20181012200227
aoml/1900183/1900183_meta.nc,846,AO,20181012200230
aoml/1900184/1900184_meta.nc,846,AO,20181012200235
aoml/1900185/1900185_meta.nc,846,AO,20181012200237
aoml/1900186/1900186_meta.nc,846,AO,20160527004226
aoml/1900187/1900187_meta.nc,846,AO,20181012200239
aoml/1900188/1900188_meta.nc,846,AO,20160527004231
aoml/1900189/1900189_meta.nc,846,AO,20210428200946
aoml/1900190/1900190_meta.nc,846,AO,20181013200209
aoml/1900191/1900191_meta.nc,846,AO,20160527005102
aoml/1900192/1900192_meta.nc,846,AO,20160527005107
aoml/1900193/1900193_meta.nc,846,AO,20160527005132
aoml/1900194/1900194_meta.nc,846,AO,20160527005122
aoml/1900195/1900195_meta.nc,846,AO,20160527005128
aoml/1900196/1900196_meta.nc,846,AO,20160527005139
aoml/1900197/1900197_meta.nc,846,AO,20160527005145
aoml/1900198/1900198_meta.nc,846,AO,20160527005146
aoml/1900199/1900199_meta.nc,846,AO,20160623145928
aoml/1900200/1900200_meta.nc,846,AO,20160623145929
aoml/1900201/1900201_meta.nc,852,AO,20210428200628
aoml/1900202/1900202_meta.nc,852,AO,20160512145743
aoml/1900203/1900203_meta.nc,852,AO,20190705200014
aoml/1900204/1900204_meta.nc,851,AO,20160519222849
aoml/1900240/1900240_meta.nc,851,AO,20181012200319
aoml/1900241/1900241_meta.nc,851,AO,20181012200324
aoml/1900242/1900242_meta.nc,851,AO,20210428200630
aoml/1900243/1900243_meta.nc,851,AO,20181012200329
aoml/1900244/1900244_meta.nc,852,AO,20190226210020
aoml/1900245/1900245_meta.nc,852,AO,20190226210020
aoml/1900246/1900246_meta.nc,851,AO,20160519222941
aoml/1900248/1900248_meta.nc,852,AO,20160519223020
aoml/1900249/1900249_meta.nc,852,AO,20160519223021
aoml/1900255/1900255_meta.nc,852,AO,20190226210021
aoml/1900256/1900256_meta.nc,851,AO,20210428200609
aoml/1900257/1900257_meta.nc,852,AO,20190226210021
aoml/1900258/1900258_meta.nc,852,AO,20160519223053
aoml/1900259/1900259_meta.nc,852,AO,20160519223051
aoml/1900260/1900260_meta.nc,852,AO,20160519223120
aoml/1900261/1900261_meta.nc,852,AO,20160519223256
aoml/1900262/1900262_meta.nc,852,AO,20160519223257
aoml/1900263/1900263_meta.nc,851,AO,20160519223300
aoml/1900264/1900264_meta.nc,851,AO,20160519223300
aoml/1900265/1900265_meta.nc,851,AO,20160519223259
aoml/1900266/1900266_meta.nc,846,AO,20160623145929
aoml/1900267/1900267_meta.nc,846,AO,20160623145930
aoml/1900268/1900268_meta.nc,846,AO,20240729143836
aoml/1900269/1900269_meta.nc,846,AO,20160623145937
aoml/1900270/1900270_meta.nc,846,AO,20181016200355
aoml/1900271/1900271_meta.nc,846,AO,20160623145940
aoml/1900272/1900272_meta.nc,846,AO,20210428201405
aoml/1900273/1900273_meta.nc,846,AO,20181016200417
aoml/1900274/1900274_meta.nc,846,AO,20181016200348
aoml/1900353/1900353_meta.nc,846,AO,20190130151234
aoml/1900354/1900354_meta.nc,846,AO,20190130151235
aoml/1900355/1900355_meta.nc,846,AO,20210428201828
aoml/1900356/1900356_meta.nc,846,AO,20190130151236
aoml/1900357/1900357_meta.nc,846,AO,20190130151237
aoml/1900358/1900358_meta.nc,846,AO,20160623151228
aoml/1900359/1900359_meta.nc,852,AO,20160519223304
aoml/1900360/1900360_meta.nc,852,AO,20160519223304
aoml/1900361/1900361_meta.nc,852,AO,20160519223302
aoml/1900362/1900362_meta.nc,851,AO,20160519223222
aoml/1900363/1900363_meta.nc,851,AO,20160519223223
aoml/1900364/1900364_meta.nc,851,AO,20160519223224
aoml/1900365/1900365_meta.nc,851,AO,20210428200946
aoml/1900366/1900366_meta.nc,852,AO,20160519223340
aoml/1900406/1900406_meta.nc,846,AO,20160623151229
aoml/1900407/1900407_meta.nc,846,AO,20160623151229
aoml/1900408/1900408_meta.nc,846,AO,20160623151230
aoml/1900409/1900409_meta.nc,846,AO,20210428204910
aoml/1900410/1900410_meta.nc,846,AO,20210428204917
aoml/1900411/1900411_meta.nc,846,AO,20210428204932
aoml/1900412/1900412_meta.nc,846,AO,20250207210021
aoml/1900413/1900413_meta.nc,846,AO,20210428205001
aoml/1900414/1900414_meta.nc,846,AO,20160623151236
aoml/1900415/1900415_meta.nc,852,AO,20160623145947
aoml/1900423/1900423_meta.nc,852,AO,20160512150638
aoml/1900424/1900424_meta.nc,852,AO,20160623145944
aoml/1900425/1900425_meta.nc,852,AO,20160623145945
aoml/1900426/1900426_meta.nc,852,AO,20160623145943
aoml/1900427/1900427_meta.nc,852,AO,20160623145942
aoml/1900428/1900428_meta.nc,852,AO,20160623145945
aoml/1900429/1900429_meta.nc,852,AO,20160623145942
aoml/1900430/1900430_meta.nc,852,AO,20160519223257
aoml/1900431/1900431_meta.nc,852,AO,20160623145946
aoml/1900432/1900432_meta.nc,846,AO,20181024200211
aoml/1900435/1900435_meta.nc,846,AO,20181024200216
aoml/1900436/1900436_meta.nc,846,AO,20160512152318
aoml/1900437/1900437_meta.nc,846,AO,20160512152319
aoml/1900438/1900438_meta.nc,846,AO,20181024200633
aoml/1900439/1900439_meta.nc,846,AO,20181024200721
aoml/1900440/1900440_meta.nc,846,AO,20180206210610
aoml/1900441/1900441_meta.nc,846,AO,20181024200724
aoml/1900442/1900442_meta.nc,846,AO,20181024200729
aoml/1900443/1900443_meta.nc,846,AO,20181024200735
aoml/1900444/1900444_meta.nc,852,AO,20160623150133
aoml/1900445/1900445_meta.nc,851,AO,20250702200129
aoml/1900446/1900446_meta.nc,852,AO,20160623150132
aoml/1900447/1900447_meta.nc,852,AO,20160623150131
aoml/1900448/1900448_meta.nc,852,AO,20160512150751
aoml/1900449/1900449_meta.nc,851,AO,20160623150057
aoml/1900487/1900487_meta.nc,852,AO,20160623150058
aoml/1900488/1900488_meta.nc,851,AO,20250702200127
aoml/1900489/1900489_meta.nc,851,AO,20160623150059
aoml/1900490/1900490_meta.nc,851,AO,20160623150155
aoml/1900491/1900491_meta.nc,852,AO,20160623150156
aoml/1900492/1900492_meta.nc,851,AO,20250702200141
aoml/1900493/1900493_meta.nc,851,AO,20181016200949
aoml/1900494/1900494_meta.nc,852,AO,20160623150306
aoml/1900495/1900495_meta.nc,851,AO,20250702200144
aoml/1900496/1900496_meta.nc,851,AO,20160623150310
aoml/1900497/1900497_meta.nc,851,AO,20160623150151
aoml/1900498/1900498_meta.nc,852,AO,20160623150150
aoml/1900499/1900499_meta.nc,851,AO,20160623150151
aoml/1900500/1900500_meta.nc,852,AO,20160623150330
aoml/1900501/1900501_meta.nc,852,AO,20160623150329
aoml/1900502/1900502_meta.nc,852,AO,20160623150328
aoml/1900503/1900503_meta.nc,852,AO,20160623150328
aoml/1900504/1900504_meta.nc,852,AO,20250702200156
aoml/1900505/1900505_meta.nc,852,AO,20160623150331
aoml/1900506/1900506_meta.nc,851,AO,20250702200158
aoml/1900525/1900525_meta.nc,852,AO,20160623150427
aoml/1900526/1900526_meta.nc,852,AO,20160623150427
aoml/1900527/1900527_meta.nc,852,AO,20250703200042
aoml/1900528/1900528_meta.nc,851,AO,20250703200043
aoml/1900529/1900529_meta.nc,852,AO,20160623150402
aoml/1900530/1900530_meta.nc,852,AO,20160623150430
aoml/1900531/1900531_meta.nc,852,AO,20250703200101
aoml/1900532/1900532_meta.nc,851,AO,20250703200107
aoml/1900533/1900533_meta.nc,852,AO,20250703200059
aoml/1900534/1900534_meta.nc,852,AO,20250703200103
aoml/1900535/1900535_meta.nc,852,AO,20160623150721
aoml/1900536/1900536_meta.nc,852,AO,20160623150720
aoml/1900537/1900537_meta.nc,852,AO,20160623150720
aoml/1900538/1900538_meta.nc,851,AO,20160623150719
aoml/1900539/1900539_meta.nc,852,AO,20160623150718
aoml/1900560/1900560_meta.nc,852,AO,20250703200057
aoml/1900561/1900561_meta.nc,852,AO,20250703200040
aoml/1900562/1900562_meta.nc,852,AO,20250703200121
aoml/1900563/1900563_meta.nc,852,AO,20250703200133
aoml/1900564/1900564_meta.nc,852,AO,20160623150746
aoml/1900565/1900565_meta.nc,851,AO,20250703200135
aoml/1900566/1900566_meta.nc,852,AO,20250703200126
aoml/1900567/1900567_meta.nc,852,AO,20250703200156
aoml/1900568/1900568_meta.nc,851,AO,20160623150834
aoml/1900569/1900569_meta.nc,852,AO,20160623150833
aoml/1900570/1900570_meta.nc,852,AO,20160623150833
aoml/1900571/1900571_meta.nc,852,AO,20160623150754
aoml/1900572/1900572_meta.nc,851,AO,20160623150755
aoml/1900573/1900573_meta.nc,852,AO,20210428203531
aoml/1900574/1900574_meta.nc,852,AO,20160512151542
aoml/1900575/1900575_meta.nc,851,AO,20210428203535
aoml/1900576/1900576_meta.nc,851,AO,20160623150836
aoml/1900577/1900577_meta.nc,851,AO,20210428203901
aoml/1900578/1900578_meta.nc,851,AO,20160623150941
aoml/1900579/1900579_meta.nc,851,AO,20210428203913
aoml/1900580/1900580_meta.nc,851,AO,20210428204117
aoml/1900581/1900581_meta.nc,851,AO,20160623151050
aoml/1900582/1900582_meta.nc,852,AO,20210428204123
aoml/1900583/1900583_meta.nc,852,AO,20160623151051
aoml/1900584/1900584_meta.nc,851,AO,20210428204126
aoml/1900635/1900635_meta.nc,852,AO,20210428204104
aoml/1900636/1900636_meta.nc,852,AO,20210428204111
aoml/1900637/1900637_meta.nc,852,AO,20210428204058
aoml/1900638/1900638_meta.nc,851,AO,20160623151046
aoml/1900639/1900639_meta.nc,852,AO,20210428204142
aoml/1900640/1900640_meta.nc,852,AO,20160623150751
aoml/1900641/1900641_meta.nc,852,AO,20250703200137
aoml/1900642/1900642_meta.nc,852,AO,20160623150752
aoml/1900643/1900643_meta.nc,852,AO,20250703200140
aoml/1900644/1900644_meta.nc,851,AO,20210428204146
aoml/1900645/1900645_meta.nc,852,AO,20210428204210
aoml/1900646/1900646_meta.nc,852,AO,20210428204152
aoml/1900647/1900647_meta.nc,851,AO,20160623150937
aoml/1900648/1900648_meta.nc,851,AO,20160623150941
aoml/1900649/1900649_meta.nc,851,AO,20210428203917
aoml/1900683/1900683_meta.nc,851,AO,20210428203909
aoml/1900684/1900684_meta.nc,851,AO,20210428203857
aoml/1900685/1900685_meta.nc,851,AO,20210428203905
aoml/1900686/1900686_meta.nc,851,AO,20210428203853
aoml/1900687/1900687_meta.nc,851,AO,20210428204347
aoml/1900688/1900688_meta.nc,852,AO,20210428204405
aoml/1900689/1900689_meta.nc,851,AO,20210428204343
aoml/1900690/1900690_meta.nc,852,AO,20210428204400
aoml/1900691/1900691_meta.nc,851,AO,20150428082159
aoml/1900692/1900692_meta.nc,851,AO,20150428082159
aoml/1900693/1900693_meta.nc,851,AO,20150428082159
aoml/1900694/1900694_meta.nc,851,AO,20150428082159
aoml/1900695/1900695_meta.nc,851,AO,20150428082159
aoml/1900696/1900696_meta.nc,851,AO,20150428082159
aoml/1900697/1900697_meta.nc,851,AO,20150428082159
aoml/1900698/1900698_meta.nc,851,AO,20150428082159
aoml/1900699/1900699_meta.nc,851,AO,20150428082159
aoml/1900700/1900700_meta.nc,851,AO,20150428082159
aoml/1900701/1900701_meta.nc,851,AO,20150428082159
aoml/1900702/1900702_meta.nc,852,AO,20210428204549
aoml/1900703/1900703_meta.nc,852,AO,20210428204553
aoml/1900704/1900704_meta.nc,852,AO,20210428204557
aoml/1900705/1900705_meta.nc,851,AO,20210428204602
aoml/1900706/1900706_meta.nc,852,AO,20160623151130
aoml/1900707/1900707_meta.nc,852,AO,20210428204450
aoml/1900708/1900708_meta.nc,851,AO,20210428204541
aoml/1900709/1900709_meta.nc,852,AO,20160512151827
aoml/1900710/1900710_meta.nc,852,AO,20210428204515
aoml/1900711/1900711_meta.nc,852,AO,20160623151121
aoml/1900712/1900712_meta.nc,852,AO,20160623151524
aoml/1900713/1900713_meta.nc,852,AO,20160623151127
aoml/1900714/1900714_meta.nc,852,AO,20160623151137
aoml/1900715/1900715_meta.nc,852,AO,20160623151136
aoml/1900716/1900716_meta.nc,851,AO,20160623151132
aoml/1900717/1900717_meta.nc,851,AO,20181017201746
aoml/1900718/1900718_meta.nc,851,AO,20181017201754
aoml/1900719/1900719_meta.nc,851,AO,20181017201742
aoml/1900720/1900720_meta.nc,851,AO,20181017201750
aoml/1900721/1900721_meta.nc,851,AO,20181017201758
aoml/1900722/1900722_meta.nc,846,AO,20160623150933
aoml/1900723/1900723_meta.nc,846,AO,20230701200018
aoml/1900724/1900724_meta.nc,846,AO,20181019201537
aoml/1900725/1900725_meta.nc,846,AO,20210428212333
aoml/1900726/1900726_meta.nc,846,AO,20210428212345
aoml/1900727/1900727_meta.nc,846,AO,20210428212355
aoml/1900728/1900728_meta.nc,846,AO,20210428212403
aoml/1900729/1900729_meta.nc,846,AO,20181019201546
aoml/1900730/1900730_meta.nc,846,AO,20181019201550
aoml/1900731/1900731_meta.nc,846,AO,20181019201555
aoml/1900732/1900732_meta.nc,851,AO,20181017201559
aoml/1900733/1900733_meta.nc,851,AO,20181017201604
aoml/1900734/1900734_meta.nc,851,AO,20181017201556
aoml/1900735/1900735_meta.nc,851,AO,20181018200232
aoml/1900736/1900736_meta.nc,851,AO,20181018200235
aoml/1900737/1900737_meta.nc,851,AO,20181018200228
aoml/1900738/1900738_meta.nc,851,AO,20160623151542
aoml/1900739/1900739_meta.nc,851,AO,20160512152248
aoml/1900740/1900740_meta.nc,851,AO,20181018200245
aoml/1900741/1900741_meta.nc,851,AO,20250709200147
aoml/1900742/1900742_meta.nc,851,AO,20160623151547
aoml/1900743/1900743_meta.nc,851,AO,20160623151604
aoml/1900744/1900744_meta.nc,851,AO,20181018200346
aoml/1900745/1900745_meta.nc,851,AO,20250709200149
aoml/1900746/1900746_meta.nc,851,AO,20181018200350
aoml/1900747/1900747_meta.nc,851,AO,20250709200153
aoml/1900748/1900748_meta.nc,851,AO,20250709200149
aoml/1900749/1900749_meta.nc,851,AO,20160623151551
aoml/1900750/1900750_meta.nc,851,AO,20181018200255
aoml/1900751/1900751_meta.nc,851,AO,20160512152254
aoml/1900752/1900752_meta.nc,851,AO,20160623151532
aoml/1900753/1900753_meta.nc,851,AO,20160623151533
aoml/1900754/1900754_meta.nc,851,AO,20181018200200
aoml/1900755/1900755_meta.nc,851,AO,20181018200203
aoml/1900756/1900756_meta.nc,851,AO,20160623151531
aoml/1900757/1900757_meta.nc,851,AO,20160623151532
aoml/1900758/1900758_meta.nc,851,AO,20181018200443
aoml/1900759/1900759_meta.nc,851,AO,20160623151622
aoml/1900760/1900760_meta.nc,851,AO,20250702200200
aoml/1900761/1900761_meta.nc,851,AO,20250709200144
aoml/1900762/1900762_meta.nc,851,AO,20250709200216
aoml/1900763/1900763_meta.nc,851,AO,20250709200238
aoml/1900764/1900764_meta.nc,851,AO,20250709200244
aoml/1900765/1900765_meta.nc,851,AO,20250709200240
aoml/1900766/1900766_meta.nc,851,AO,20250709200242
aoml/1900767/1900767_meta.nc,851,AO,20250709200246
aoml/1900768/1900768_meta.nc,851,AO,20160623151754
aoml/1900769/1900769_meta.nc,851,AO,20250709200220
aoml/1900770/1900770_meta.nc,851,AO,20181019200620
aoml/1900771/1900771_meta.nc,851,AO,20160623152002
aoml/1900772/1900772_meta.nc,851,AO,20250709200247
aoml/1900773/1900773_meta.nc,851,AO,20250709200249
aoml/1900774/1900774_meta.nc,851,AO,20250709200251
aoml/1900775/1900775_meta.nc,851,AO,20160623151751
aoml/1900776/1900776_meta.nc,851,AO,20250709200253
aoml/1900777/1900777_meta.nc,851,AO,20210428213044
aoml/1900778/1900778_meta.nc,851,AO,20210428213041
aoml/1900779/1900779_meta.nc,851,AO,20160623152148
aoml/1900780/1900780_meta.nc,851,AO,20170419003559
aoml/1900781/1900781_meta.nc,851,AO,20160623152154
aoml/1900782/1900782_meta.nc,851,AO,20160623152153
aoml/1900783/1900783_meta.nc,851,AO,20160623152152
aoml/1900784/1900784_meta.nc,851,AO,20160512152943
aoml/1900785/1900785_meta.nc,851,AO,20160623152227
aoml/1900786/1900786_meta.nc,851,AO,20160623152229
aoml/1900787/1900787_meta.nc,851,AO,20210428213125
aoml/1900788/1900788_meta.nc,851,AO,20210428213128
aoml/1900789/1900789_meta.nc,851,AO,20210428213121
aoml/1900790/1900790_meta.nc,851,AO,20160623152210
aoml/1900791/1900791_meta.nc,851,AO,20210428213056
aoml/1900792/1900792_meta.nc,851,AO,20210428213058
aoml/1900793/1900793_meta.nc,851,AO,20160512153123
aoml/1900794/1900794_meta.nc,851,AO,20210428213910
aoml/1900795/1900795_meta.nc,851,AO,20210428213854
aoml/1900796/1900796_meta.nc,851,AO,20250709200157
aoml/1900797/1900797_meta.nc,851,AO,20160623152406
aoml/1900798/1900798_meta.nc,851,AO,20160623152404
aoml/1900799/1900799_meta.nc,851,AO,20210428213919
aoml/1900800/1900800_meta.nc,851,AO,20160623152411
aoml/1900801/1900801_meta.nc,851,AO,20190129174512
aoml/1900802/1900802_meta.nc,851,AO,20160623152142
aoml/1900803/1900803_meta.nc,851,AO,20160623152143
aoml/1900804/1900804_meta.nc,851,AO,20151218132115
aoml/1900805/1900805_meta.nc,851,AO,20160411145446
aoml/1900806/1900806_meta.nc,851,AO,20160504150900
aoml/1900807/1900807_meta.nc,851,AO,20150428082159
aoml/1900808/1900808_meta.nc,851,AO,20150810121845
aoml/1900809/1900809_meta.nc,851,AO,20150810121545
aoml/1900810/1900810_meta.nc,851,AO,20160504150735
aoml/1900811/1900811_meta.nc,851,AO,20150428082159
aoml/1900812/1900812_meta.nc,851,AO,20150504101237
aoml/1900813/1900813_meta.nc,851,AO,20150504160403
aoml/1900814/1900814_meta.nc,846,AO,20160623151958
aoml/1900815/1900815_meta.nc,846,AO,20210428212011
aoml/1900816/1900816_meta.nc,846,AO,20210428212028
aoml/1900817/1900817_meta.nc,846,AO,20210428212030

##### 2. NetCDF files

In [54]:
# Check for CF Conventions declaration
def check_cf_conventions(nc_file):    
    if 'Conventions' in nc_file.ncattrs():
        print(f"Conventions: {nc_file.Conventions}")
        if "CF" in nc_file.Conventions:
            print("✅ CF Conventions are declared.")
        else:
            print("⚠️ Conventions declared, but not CF.")
    else:
        print("❌ No 'Conventions' attribute found.")

    print("\nCF Standard Names in Variables:")
    found = False
    for name, var in nc_file.variables.items():
        if hasattr(var, 'standard_name'):
            print(f"{name}: standard_name = {var.standard_name}")
            found = True

    if not found:
        print("⚠️ No 'standard_name' attributes found in any variables.")

    for name, var in nc_file.variables.items():
        if hasattr(var, 'units'):
            print(f"{name}: units = {var.units}")
    
    return None

In [55]:
# Example profile nc file
nc_profile = Dataset("files_euroargo_https/19970728_prof.nc")
check_cf_conventions(nc_profile)

Conventions: Argo-3.1 CF-1.6
✅ CF Conventions are declared.

CF Standard Names in Variables:
JULD: standard_name = time
LATITUDE: standard_name = latitude
LONGITUDE: standard_name = longitude
PRES: standard_name = sea_water_pressure
PRES_ADJUSTED: standard_name = sea_water_pressure
TEMP: standard_name = sea_water_temperature
TEMP_ADJUSTED: standard_name = sea_water_temperature
JULD: units = days since 1950-01-01 00:00:00 UTC
JULD_LOCATION: units = days since 1950-01-01 00:00:00 UTC
LATITUDE: units = degree_north
LONGITUDE: units = degree_east
PRES: units = decibar
PRES_ADJUSTED: units = decibar
PRES_ADJUSTED_ERROR: units = decibar
TEMP: units = degree_Celsius
TEMP_ADJUSTED: units = degree_Celsius
TEMP_ADJUSTED_ERROR: units = degree_Celsius
HISTORY_START_PRES: units = decibar
HISTORY_STOP_PRES: units = decibar

In [56]:
# Example meta nc file
nc_meta_file = Dataset("files_euroargo_https/1902115_meta_aux.nc")
check_cf_conventions(nc_meta_file)

Conventions: CF-1.6 Coriolis-Argo-Aux-1.0
✅ CF Conventions are declared.

CF Standard Names in Variables:
⚠️ No 'standard_name' attributes found in any variables.

In [57]:
# Example tech nc file
nc_tech_file = Dataset("files_euroargo_https/1902115_tech_aux.nc")
check_cf_conventions(nc_tech_file)

Conventions: CF-1.6 Coriolis-Argo-Aux-1.0
✅ CF Conventions are declared.

CF Standard Names in Variables:
JULD: standard_name = time
JULD_ADJUSTED: standard_name = time
JULD: units = days since 1950-01-01 00:00:00 UTC
JULD_ADJUSTED: units = days since 1950-01-01 00:00:00 UTC
VALVE_ACTION_DURATION: units = csec
PUMP_ACTION_DURATION: units = csec

##### 3. CSV files

In [26]:
csv_url = "https://data-argo.ifremer.fr/etc/ObjectiveAnalysisWarning/kordi/ar_scoop2_KO_20141107123100.csv"
df = pd.read_csv(csv_url)
df

,DAC_CODE,PLATFORM_CODE,CV_NUMBER,DATE_UPDATE,DIRECTION,WEB_URL,PARAMETER,START_IMMERSION,STOP_IMMERSION,OLD_QC,NEW_QC
0,KO,2900922,258,07/10/2014 00:00:00,A,http://www.ifremer.fr/co-argoFloats/station?st...,PSAL,86.0,86.0,1,4
1,KO,2900922,258,07/10/2014 00:00:00,A,http://www.ifremer.fr/co-argoFloats/station?st...,TEMP,48.9,48.9,1,4
2,KO,2900922,258,07/10/2014 00:00:00,A,http://www.ifremer.fr/co-argoFloats/station?st...,TEMP,86.0,86.0,1,4

In [32]:
csv_url = "https://data-argo.ifremer.fr/etc/Report_ObjectiveAnalysisWarning/csv_drift/2021/drift_september2021_new.csv"
df = pd.read_csv(csv_url, encoding='latin1',  sep=';')
df

,DAC,WMO,PI,First station in alert,First cycle\n in alert,Last Station\n in alert,Last cycle\n in alert,QC level in RT in Coriolis DB,Description,SENSOR_MODEL,SERIAL_NU,"Failure_Type\nfor Coriolis DB (1-drift, 2-bias, 3-weird, 4-wrecked, 5-pressure, 6-adjustement issue)",Comment\nAll drift mentions are SUSPICION\ndrift value mentions are visual impression\nsurrounding profiles = close in space (position diff < 2 degrees latitude/longitude) and in time (date diff < 5 years)
0,NEW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AOML,1902200.0,GREGORY C. JOHNSON,2021/07/06,111.0,2021/08/15,115.0,3 & 4,Argo PMEL,SBE41CP,09909,1.0,"Drift and bad profiles, some missing cycles"
2,AOML,3901224.0,"BRECK OWENS, STEVEN JAYNE, P.E. ROBBINS",2021/08/31,224.0,2021/09/29,227.0,4,Argo WHOI,SBE41CP,7145,1.0,Jump
3,AOML,3902244.0,"WIJFFELS, JANES, ROBBINS",2021/09/29,67.0,NaN,NaN,3,Argo WHOI,SBE41CP,11061,1.0,Drift starting ?
4,AOML,4901659.0,GREGORY C. JOHNSON,2021/10/01,262.0,NaN,NaN,3,Argo PMEL,SBE41CP,5925,1.0,Slight Drift
5,AOML,4903198.0,GREGORY C. JOHNSON,2021/09/04,91.0,2021/09/14,92.0,3,Argo PMEL,SBE41CP,11161,1.0,Slight Drift
6,AOML,4903358.0,"WIJFFELS, JANES, ROBBINS",2021/09/21,16.0,2021/10/01,17.0,3,Argo WHOI,SBE41CP,12673,1.0,Drift
7,AOML,5904111.0,STEPHEN RISER,2021/09/18,293.0,2021/09/28,294.0,3,Argo UW,SBE41,5954,1.0,Slight Drift ? Or strange upper part of profile
8,AOML,5904707.0,GREGORY C. JOHNSON,2021/09/13,211.0,2021/10/03,213.0,3,Argo PMEL,SBE41CP,6299,1.0,Slight Drift
9,AOML,5904778.0,STEPHEN RISER,2021/09/21,185.0,2021/10/01,186.0,3,Argo UW,SBE41CP,7763,1.0,Slight Drift
10,AOML,5904948.0,GREGORY C. JOHNSON,2021/09/19,171.0,2021/09/29,172.0,4,Argo PMEL,SBE41CP,08641,1.0,"Jump, drift ?"
11,AOML,5905083.0,STEPHEN RISER,2021/09/15,167.0,2021/09/25,168.0,3,Argo UW,SBE41CP,6414,1.0,Drift
12,AOML,5905677.0,DEAN ROEMMICH,2021/10/02,136.0,NaN,NaN,4,Argo SIO,SBE41CP_V7.2.5,9651,3.0,Bad profile
13,AOML,5906012.0,STEPHEN RISER,2021/09/17,99.0,2021/09/27,100.0,3,Argo UW,SBE41CP,9836,3.0,Jump but strange profile
14,AOML,5906040.0,STEPHEN RISER/KEN JOHNSON,2021/09/16,297.0,2021/09/22,299.0,3,Argo UW-SOCCOM,SBE41CP,10454,1.0,Drift
15,AOML,5906431.0,"DEAN ROEMMICH, SARAH PURKEY, NATHALIE ZILBERMA...",2021/09/23,10.0,2021/10/03,11.0,3,Argo SIO,SBE41CP_V7.2.5,12038,1.0,Drift
16,AOML,5906696.0,"DEAN ROEMMICH, SARAH PURKEY, NATHALIE ZILBERMA...",2021/09/26,1.0,2021/09/29,4.0,3,Argo SIO,SBE41CP_V7.2.5,12379,1.0,Drift
17,BODC,3902400.0,John Turton,2021/09/18,67.0,2021/09/28,68.0,3,Argo UK,SBE41CP_V7.2.5,10893,1.0,Drift
18,BODC,6901926.0,Diarmuid O'Conchubhair,2021/09/29,200.0,NaN,NaN,3,Argo IRELAND,SBE41,8837,1.0,Drift
19,CORIOLIS,3901921.0,Jose Lluis Pelegri,2021/09/02,120.0,2021/10/02,124.0,3,ARGO MOCCA,SBE41CP_V7.2.5,8305,1.0,Slight Drift
20,CORIOLIS,3901990.0,Romain Cancouet,2021/10/01,108.0,NaN,NaN,4,ARGO MOCCA,SBE41CP_V7.2.5,10104,3.0,Bad profile
21,CORIOLIS,6902781.0,Sabrina SPEICH,2021/09/01,131.0,2021/10/01,134.0,3,CORIOLIS,SBE41CP_V7.2.5,8976,1.0,Drift
22,CORIOLIS,6903038.0,Damien Desbruyères,2021/09/27,11.0,NaN,NaN,4,NaN,SBE41CP_V7.2.5,12286,3.0,Bad profiles
23,CORIOLIS,6903239.0,Pierre-Marie Poulain,2021/09/29,258.0,2021/10/04,259.0,3,ARGO Italy,SBE41CP_V7.2.5,10063,1.0,Jump ? Drift ?
24,CORIOLIS,7900500.0,Birgit Klein,2021/08/30,172.0,NaN,NaN,4 (T & S),Argo BSH,SBE41,41-8833,3.0,Strange profile
25,CORIOLIS,7900570.0,Birgit Klein,2021/09/15,45.0,2021/09/25,46.0,3,Argo BSH,SBE41CP,41-12684,1.0,Drift
26,CSIRO,5905182.0,Susan Wijffels --> Grey List,2021/09/06,176.0,NaN,NaN,3,ARGO Australia,SBE41CP_V7.2.5,8180,3.0,"Strange behaviour, drift ? Different water mas..."
27,CSIRO,7900616.0,Susan Wijffels --> Grey List,2021/09/18,210.0,NaN,NaN,3,ARGO Australia,SBE41CP_V2,7111,3.0,"Strange behaviour, drift ? Different water mas..."
28,INCOIS,2902182.0,RAVICHANDRAN,2021/09/12,221.0,NaN,NaN,3,Indian Argo,SBE41CP,7252,1.0,Slight Drift
29,INCOIS,2902210.0,RAVICHANDRAN,2021/09/24,233.0,2021/10/04,234.0,3,Indian Argo,SBE41CP,8358,1.0,Slight Drift
30,JMA,5905861.0,JAMSTEC,2021/09/21,89.0,2021/10/01,90.0,3,Argo JAMSTEC,SBE41CP_V7.2.5,10964,1.0,Slight Drift
31,JMA,5905863.0,JAMSTEC,2021/09/28,78.0,NaN,NaN,3,Argo JAMSTEC,SBE41CP_V7.2.5,10966,1.0,Slight Drift
32,JMA,5906390.0,JAMSTEC,2021/08/30,20.0,2021/09/29,23.0,3 (T) 4 (S),Argo JAMSTEC,SBE41CP_V7.2.5,11352,1.0,Drift T & S with jump for S ?

##### 4. HTML files

In [36]:
def check_standard_vocabularies(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    findings = {
        "meta_tags": [],
        "rdfa_properties": [],
        "schema_org_items": [],
        "json_ld": []
    }

    # Check <meta> tags for Dublin Core or schema-related names
    for meta in soup.find_all("meta"):
        name = meta.get("name", "")
        if name and ("dc" in name.lower() or "dublin" in name.lower() or "schema" in name.lower()):
            findings["meta_tags"].append(str(meta))

    # Check RDFa (property, typeof, vocab attributes)
    for tag in soup.find_all(attrs={"property": True}):
        findings["rdfa_properties"].append(str(tag))

    # Check Schema.org via itemscope/itemtype/itemprop
    for tag in soup.find_all(attrs={"itemscope": True, "itemtype": True}):
        findings["schema_org_items"].append(str(tag))

    # Check JSON-LD blocks
    for script in soup.find_all("script", type="application/ld+json"):
        try:
            findings["json_ld"].append(json.loads(script.string))
        except Exception:
            findings["json_ld"].append(script.string)

    return findings

In [38]:
html_url = "https://data-argo.ifremer.fr/aux/aoml/1901608/1901608_tech_aux.html"
results = check_standard_vocabularies(html_url)

print("---- Meta Tags (Dublin Core / Schema) ----")
for m in results["meta_tags"]:
    print(m)

print("\n---- RDFa Properties ----")
for r in results["rdfa_properties"]:
    print(r)

print("\n---- Schema.org Items ----")
for s in results["schema_org_items"]:
    print(s)

print("\n---- JSON-LD ----")
for j in results["json_ld"]:
    print(j)

---- Meta Tags (Dublin Core / Schema) ----

---- RDFa Properties ----

---- Schema.org Items ----

---- JSON-LD ----

Findings on use of standard vocabularies and ontologies in various file types:  
**Text files**
- No explicit reference to controlled vocabularies or ontologies.
- Codes are used (e.g., profiler_type, institution) but their meaning is not documented or mapped to external standards.
- Column semantics are unclear in places (e.g., file), which reduces interpretability.
- Some concepts such as project and institution could, in principle, be unambiguously linked to external identifiers or URIs, but this is not implemented.

**NetCDF files**
- CF (Climate and Forecast) conventions are explicitly declared, ensuring standardization of variable names and units.
- Use of recognized vocabularies and ontologies is evident (see [interop_euroargo_erddap_service](./interop_euroargo_erddap_service.ipynb) for detailed exploration).
- This structured adherence to standards makes NetCDF files the most semantically interoperable of the formats assessed.

**CSV files**
- Date formats are present but not ISO 8601 compliant (YYYY-MM-DD), limiting interoperability.
- No geographic metadata is provided in the assessed files, preventing conformance with ISO 19115 standards for geospatial information.
- No explicit declaration of CF conventions, although the PARAMETER column in ar_scoop2_KO_20141107123100.csv suggests partial use of standard names.
- Heavy reliance on codes (e.g., DAC_CODE, QC flags) without external mapping, making interpretation difficult.
- The PI column shows inconsistent naming conventions (uppercase vs. capitalized).
- Overall, CSV files show very limited use of standard vocabularies or ontologies.

**HTML files**
- No evidence of controlled vocabularies, ontologies, or machine-readable metadata standards (e.g., Dublin Core, Schema.org, RDFa, JSON-LD) was found in the assessed pages.

*(documentation contains some information relating to semantics: https://argo.ucsd.edu/data/data-from-gdacs/)*

**Notes on granularity**  

Data granularity refers to the level of detail at which data and metadata are made available.
- Granularity of metadata:  
Metadata is typically provided at the file level.  
It can either be accessed through separate metadata files (retrieved by navigating directory structures) or found embedded directly within the data files themselves.

- Granularity of data:  
Data is also provided at the file level, with each file containing the actual ocean measurements or observations.  
Accessing these files may require navigating directory structures or constructing download links by combining a base URL with relative paths. In some cases, an additional step is necessary, where the base URL must be combined with paths listed inside the metadata files to obtain the actual NetCDF data.