In [2]:
import pandas as pd
import requests
from jsonschema import validate, ValidationError
from accessibility import check_endpoint
from summarize import * #json_keys, data_frame

### Interoperability Assessment of EuroArgo JSON api (Floats data)

**Endpoint documentation**

API documentation (swagger): https://dataselection.euro-argo.eu/swagger-ui/index.html

### Endpoint

In [3]:
base = "https://dataselection.euro-argo.eu"

##### Table Of Content

- [Exploring the JSON API](#exploring-the-json-api)
- [Technical interoperability](#technical-interoperability)
    - [Standards compliance](#standards-compliance) 
    - [Interface consistency](#interface-consistency) 
    - [Versioning & Backward compatibility](#versioning-and-backwards-compatibility) 

- [Semantic interoperability](#semantic-interoperability)
    - [Documentation](#documentation) 
    - [Metadata](#metadata)
    - [Shared Vocabulary & Ontologies](#shared-vocabularies-and-ontologies)
    - [Contextual Meaning](#contextual-meaning) 
- ([note on Data Granularity](#note-on-data-granularity))

### Exploring the JSON API

Exploration of the API was done through the swagger documentation and for GET requests also below in this notebook:

**Basins** (get basins names as a tree)

In [5]:
basins_url = "https://dataselection.euro-argo.eu/api/basins-tree"

basin_md = requests.get(basins_url).json()

summary = json_keys(basin_md)

basin_md_summ = pd.DataFrame([
    {
        "Property": key,
        "Count": info["count"],
        "Types": ', '.join(info["types"]),
        "Example": info["example"]
    }
    for key, info in summary.items()
])
basin_md_summ.to_csv("files_euroargo_jsonapi/ARGO_JSONAPI_floatsdata_basins.csv", index=False)
basin_md_summ

,Property,Count,Types,Example
0,id,11,int,23617
1,name,11,str,ARCTIC OCEAN
2,subBasins,11,list,"[{'id': 24027, 'name': 'KARA SEA'}, {'id': 240..."
3,subBasins.id,236,int,26579
4,subBasins.name,236,str,FRAM STRAIT

This endpoint returns a list of 11 ocean basins and 236 sub-basins. The data model can be visualized as:  
![image.png](images/ARGO_JSONAPI_oceanbasins.drawio.png)

**Cycle by cycle-id** (get a cycle metadata by cycleId)

In [6]:
cycle_url = "https://dataselection.euro-argo.eu/api/find-by-id/760094"

cycle_md = requests.get(cycle_url).json()

summary = json_keys(cycle_md)

cycle_md_summ= pd.DataFrame([
    {
        "Property": key,
        "Count": info["count"],
        "Types": ', '.join(info["types"]),
        "Example": info["example"]
    }
    for key, info in summary.items()
])
cycle_md_summ.to_csv("files_euroargo_jsonapi/ARGO_JSONAPI_floatsdata_cycle.csv", index=False)
cycle_md_summ

,Property,Count,Types,Example
0,id,1,int,760094
1,cvNumber,1,int,1
2,startDate,1,str,2008-03-23T02:00:54.000+0000
3,endDate,1,str,2008-03-23T02:00:54.000+0000
4,coordinate,1,dict,"{'lat': -28.184, 'lon': -22.997}"
5,coordinate.lat,1,float,-28.184
6,coordinate.lon,1,float,-22.997
7,globalGeoShapeField,1,dict,"{'x': -22.997, 'y': -28.184, 'type': 'Point', ..."
8,globalGeoShapeField.x,1,float,-22.997
9,globalGeoShapeField.y,1,float,-28.184
10,globalGeoShapeField.type,1,str,Point
11,globalGeoShapeField.coordinates,1,list,"[-22.997, -28.184]"
12,platformCode,1,str,3900675
13,positionQc,1,str,1
14,dateQc,1,str,1
15,cycleQcState,1,str,Good
16,pmax,1,float,1820.0
17,stations,1,list,"[{'stationId': 5933705, 'coordinate': {'lat': ..."
18,stations.stationId,1,int,5933705
19,stations.coordinate,1,dict,"{'lat': -28.184, 'lon': -22.997}"
20,stations.coordinate.lat,1,float,-28.184
21,stations.coordinate.lon,1,float,-22.997
22,stations.cvNumber,1,int,1
23,stations.positionQc,1,str,1
24,stations.dateQc,1,str,1
25,stations.type,1,str,Primary sampling: averaged [data averaged with...
26,stations.direction,1,str,A
27,stations.date,1,str,2008-03-23T02:00:54.000+0000
28,stations.level,1,int,79
29,stations.primary,1,bool,True
30,stations.syntheticSampling,1,bool,False
31,stations.physicalParameters,1,list,"[66, 35, 68, 70, 28, 30]"
32,stationsId,1,list,[5933705]
33,basins,1,list,"[ATLANTIC OCEAN, SOUTHWEST ATLANTIC OCEAN (20W)]"
34,parameters,1,list,"[TEMP, PRES, PSAL]"
35,networkCodes,1,list,[CORE]
36,groupCodes,1,list,[Public context to visualize platforms in eule...
37,deploymentDate,1,str,2008-03-22T11:45:00.000+0000
38,deploymentYear,1,str,2008
39,countryLabel,1,str,United States
40,institutionLabel,1,str,Woods Hole Oceanographic Institution
41,telecomCode,1,str,ARGOS
42,dacCode,1,str,AOML
43,platformTypeCode,1,str,SOLO_W
44,pI,1,str,BRECK OWENS
45,statusCode,1,str,I
46,sensors,1,list,"[CTD_TEMP, CTD_CNDC, CTD_PRES]"
47,dataMode,1,str,D
48,lastUpdateDate,1,str,2025-08-17T16:00:56.873+0000
49,level,1,int,79
50,physicalParameters,1,list,"[{'code': 66, 'labelWithCode': '66#Sea pressur..."
51,physicalParameters.code,3,int,70
52,physicalParameters.labelWithCode,3,str,70#Practical salinity adjusted

The endpoint returns metadata associated with a specific cycle Id. The data model can be visualized as follows:  
![image.png](images/ARGO_JSONAPI_cycle.drawio.png)

**Cycle by platformID and cvNumber** (get a cycle metadata by platformId and cvNumber)

In [7]:
cycle2_url = "https://dataselection.euro-argo.eu/api/find-by-platformid/3900675/cvnumber/1"

cycle2_md = requests.get(cycle2_url).json()

summary = json_keys(cycle2_md)

cycle2_md_summ = pd.DataFrame([
    {
        "Property": key,
        "Count": info["count"],
        "Types": ', '.join(info["types"]),
        "Example": info["example"]
    }
    for key, info in summary.items()
])
cycle2_md_summ.to_csv("files_euroargo_jsonapi/ARGO_JSONAPI_floatsdata_cycle.csv", index=False)
cycle2_md_summ
# returns same cycle metadata as 'Cycle by cycle-id'

,Property,Count,Types,Example
0,id,1,int,760094
1,cvNumber,1,int,1
2,startDate,1,str,2008-03-23T02:00:54.000+0000
3,endDate,1,str,2008-03-23T02:00:54.000+0000
4,coordinate,1,dict,"{'lat': -28.184, 'lon': -22.997}"
5,coordinate.lat,1,float,-28.184
6,coordinate.lon,1,float,-22.997
7,globalGeoShapeField,1,dict,"{'x': -22.997, 'y': -28.184, 'type': 'Point', ..."
8,globalGeoShapeField.x,1,float,-22.997
9,globalGeoShapeField.y,1,float,-28.184
10,globalGeoShapeField.type,1,str,Point
11,globalGeoShapeField.coordinates,1,list,"[-22.997, -28.184]"
12,platformCode,1,str,3900675
13,positionQc,1,str,1
14,dateQc,1,str,1
15,cycleQcState,1,str,Good
16,pmax,1,float,1820.0
17,stations,1,list,"[{'stationId': 5933705, 'coordinate': {'lat': ..."
18,stations.stationId,1,int,5933705
19,stations.coordinate,1,dict,"{'lat': -28.184, 'lon': -22.997}"
20,stations.coordinate.lat,1,float,-28.184
21,stations.coordinate.lon,1,float,-22.997
22,stations.cvNumber,1,int,1
23,stations.positionQc,1,str,1
24,stations.dateQc,1,str,1
25,stations.type,1,str,Primary sampling: averaged [data averaged with...
26,stations.direction,1,str,A
27,stations.date,1,str,2008-03-23T02:00:54.000+0000
28,stations.level,1,int,79
29,stations.primary,1,bool,True
30,stations.syntheticSampling,1,bool,False
31,stations.physicalParameters,1,list,"[66, 35, 68, 70, 28, 30]"
32,stationsId,1,list,[5933705]
33,basins,1,list,"[ATLANTIC OCEAN, SOUTHWEST ATLANTIC OCEAN (20W)]"
34,parameters,1,list,"[TEMP, PRES, PSAL]"
35,networkCodes,1,list,[CORE]
36,groupCodes,1,list,[Public context to visualize platforms in eule...
37,deploymentDate,1,str,2008-03-22T11:45:00.000+0000
38,deploymentYear,1,str,2008
39,countryLabel,1,str,United States
40,institutionLabel,1,str,Woods Hole Oceanographic Institution
41,telecomCode,1,str,ARGOS
42,dacCode,1,str,AOML
43,platformTypeCode,1,str,SOLO_W
44,pI,1,str,BRECK OWENS
45,statusCode,1,str,I
46,sensors,1,list,"[CTD_TEMP, CTD_CNDC, CTD_PRES]"
47,dataMode,1,str,D
48,lastUpdateDate,1,str,2025-08-17T16:00:56.873+0000
49,level,1,int,79
50,physicalParameters,1,list,"[{'code': 66, 'labelWithCode': '66#Sea pressur..."
51,physicalParameters.code,3,int,70
52,physicalParameters.labelWithCode,3,str,70#Practical salinity adjusted

**Trajectory by platformID** (get a cycle trajectory by platformId)

In [8]:
trajectory_url = "https://dataselection.euro-argo.eu/api/trajectory/3900675"

traj_md = requests.get(trajectory_url).json()

summary = json_keys(traj_md)

traj_md_summ = pd.DataFrame([
    {
        "Property": key,
        "Count": info["count"],
        "Types": ', '.join(info["types"]),
        "Example": info["example"]
    }
    for key, info in summary.items()
])
traj_md_summ.to_csv("files_euroargo_jsonapi/ARGO_JSONAPI_floatsdata_trajectory.csv", index=False)
traj_md_summ

         Property  Count  Types                           Example
0              id    116    int                           1199770
1        cvNumber    116    int                                60
2      coordinate    116   dict  {'lat': -27.449, 'lon': -33.858}
3  coordinate.lat    116  float                           -27.449
4  coordinate.lon    116  float                           -33.858
5           level    116    int                                 0

The endpoint returns metadata associated with a specific trajectory based on a cycle Id. The data model can be visualized as follows:  
![image.png](images/ARGO_JSONAPI_traj.drawio.png)

API returns:
  - 19045 Floats:
    - described by 39 properties (many more when taking nested properties into account (see diagram for overview))

  - 11 Basins:
    - described by 3 properties
    - 236 sub-basins

  - 900+ Cycles:
    - described by 30 properties (51 taking nested properties into account)
    - no exact number on total number of cycles

### Technical Interoperability

#### Standards compliance 
*Involves checking compliance to HTTP standard, JSON schema, JSON API spec*

In [4]:
# various endpoints
urls = [
    'https://dataselection.euro-argo.eu/api',                                           #base
    'https://dataselection.euro-argo.eu/api/basins-tree',                               #example endpoint from documentation
    'https://dataselection.euro-argo.eu/api/find-by-id/760094',                         #example endpoint from documentation, with specified input parameter 
    'https://dataselection.euro-argo.eu/api/find-by-id',                                #faulty endpoint - missing input parameter 'station ID'
    'https://dataselection.euro-argo.eu/api/find-by-platformid/3900675/cvnumber/1',     #example endpoint from documentation, with multiple specified input parameters 
    'https://dataselection.euro-argo.eu/api/find-by-platformid/3900675',                #faulty endpoint
    'https://dataselection.euro-argo.eu/api/find-by-platformid/3900675/cvnumber/',      #faulty endpoint
    'https://dataselection.euro-argo.eu/api/trajectory/3900675'                         #example endpoint from documentation, with specified input parameter 
]

# headers of interest
important_headers = [
    "Content-Type",
    "Content-Length",
    "Content-Encoding",
    "Transfer-Encoding",
    "Vary",
    "Accept",
    "Accept-Encoding",
    "Accept-Language",
    "Server",
    "Date",
    "Strict-Transport-Security"
]

for url in urls:
    print("="*100)
    print(f"🔗 URL: {url}")
    try:
        r = requests.get(url, timeout=10)
        print(f"Status code: {r.status_code}\n")

        # filter only important headers
        headers_filtered = {k: v for k, v in r.headers.items() if k in important_headers}
        
        print("📌 Relevant headers:")
        if headers_filtered:
            for k, v in headers_filtered.items():
                print(f"   {k}: {v}")
        else:
            print("   (none of the selected headers present)")
        
        # try parsing response
        print("\n📌 Response preview:")
        try:
            data = r.json()
            if isinstance(data, dict):
                print("   JSON object with keys:", list(data.keys()))
            elif isinstance(data, list):
                print(f"   JSON list with {len(data)} items")
            else:
                print("   JSON response (other type)")
        except ValueError:
            print("   Text response (first 300 chars):")
            print("   " + r.text[:300].replace("\n", " ") + " ...")
    
    except requests.exceptions.RequestException as e:
        print(f"❌ Request failed: {e}")

====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:58 GMT
   Server: Apache
   Content-Type: text/html
   Vary: Accept-Encoding
   Content-Encoding: gzip
   Transfer-Encoding: chunked

📌 Response preview:
   Text response (first 300 chars):
   <!doctype html> <html lang="en" data-beasties-container> <head>   <meta charset="utf-8">   <title>Euro Argo Data Selection</title>   <base href="/">   <meta name="viewport" content="width=device-width, initial-scale=1">   <meta name="robots" content="index,nofollow">   <link rel="icon" type="image/x ...
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/basins-tree
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:58 GMT
   Server: Apache
   Content-Type: application/json
   Transfer-Encoding: chunked

📌 Response preview:
   JSON list with 11 items
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/find-by-id/760094
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:58 GMT
   Server: Apache
   Content-Type: application/json
   Transfer-Encoding: chunked

📌 Response preview:
   JSON object with keys: ['id', 'cvNumber', 'startDate', 'endDate', 'coordinate', 'globalGeoShapeField', 'platformCode', 'positionQc', 'dateQc', 'cycleQcState', 'pmax', 'stations', 'stationsId', 'basins', 'parameters', 'networkCodes', 'groupCodes', 'deploymentDate', 'deploymentYear', 'countryLabel', 'institutionLabel', 'telecomCode', 'dacCode', 'platformTypeCode', 'pI', 'statusCode', 'sensors', 'dataMode', 'lastUpdateDate', 'level', 'physicalParameters']
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/find-by-id
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:58 GMT
   Server: Apache
   Content-Type: text/html
   Vary: Accept-Encoding
   Content-Encoding: gzip
   Transfer-Encoding: chunked

📌 Response preview:
   Text response (first 300 chars):
   <!doctype html> <html lang="en" data-beasties-container> <head>   <meta charset="utf-8">   <title>Euro Argo Data Selection</title>   <base href="/">   <meta name="viewport" content="width=device-width, initial-scale=1">   <meta name="robots" content="index,nofollow">   <link rel="icon" type="image/x ...
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/find-by-platformid/3900675/cvnumber/1
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:59 GMT
   Server: Apache
   Content-Type: application/json
   Transfer-Encoding: chunked

📌 Response preview:
   JSON object with keys: ['id', 'cvNumber', 'startDate', 'endDate', 'coordinate', 'globalGeoShapeField', 'platformCode', 'positionQc', 'dateQc', 'cycleQcState', 'pmax', 'stations', 'stationsId', 'basins', 'parameters', 'networkCodes', 'groupCodes', 'deploymentDate', 'deploymentYear', 'countryLabel', 'institutionLabel', 'telecomCode', 'dacCode', 'platformTypeCode', 'pI', 'statusCode', 'sensors', 'dataMode', 'lastUpdateDate', 'level', 'physicalParameters']
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/find-by-platformid/3900675
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:59 GMT
   Server: Apache
   Content-Type: text/html
   Vary: Accept-Encoding
   Content-Encoding: gzip
   Transfer-Encoding: chunked

📌 Response preview:
   Text response (first 300 chars):
   <!doctype html> <html lang="en" data-beasties-container> <head>   <meta charset="utf-8">   <title>Euro Argo Data Selection</title>   <base href="/">   <meta name="viewport" content="width=device-width, initial-scale=1">   <meta name="robots" content="index,nofollow">   <link rel="icon" type="image/x ...
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/find-by-platformid/3900675/cvnumber/
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:59 GMT
   Server: Apache
   Content-Type: text/html
   Vary: Accept-Encoding
   Content-Encoding: gzip
   Transfer-Encoding: chunked

📌 Response preview:
   Text response (first 300 chars):
   <!doctype html> <html lang="en" data-beasties-container> <head>   <meta charset="utf-8">   <title>Euro Argo Data Selection</title>   <base href="/">   <meta name="viewport" content="width=device-width, initial-scale=1">   <meta name="robots" content="index,nofollow">   <link rel="icon" type="image/x ...
====================================================================================================
🔗 URL: https://dataselection.euro-argo.eu/api/trajectory/3900675
Status code: 200

📌 Relevant headers:
   Date: Wed, 27 Aug 2025 11:53:59 GMT
   Server: Apache
   Content-Type: application/json
   Transfer-Encoding: chunked

📌 Response preview:
   JSON list with 116 items

In [ ]:
# Cycle metadata schema (from api documentation)
schema = {
  "highlightFields": {
    "additionalProp1": [
      "string"
    ],
    "additionalProp2": [
      "string"
    ],
    "additionalProp3": [
      "string"
    ]
  },
  "id": 0,
  "cvNumber": 0,
  "startDate": "2025-08-18T11:54:25.402Z",
  "endDate": "2025-08-18T11:54:25.402Z",
  "coordinate": {
    "lat": 0,
    "lon": 0
  },
  "globalGeoShapeField": {
    "type": "string",
    "coordinates": {}
  },
  "platformCode": "string",
  "positionQc": "string",
  "dateQc": "string",
  "cycleQcState": "string",
  "grounded": "true",
  "pmax": 0,
  "surfacePressure": 0,
  "surfaceTemperature": 0,
  "surfaceSalinity": 0,
  "bottomPressure": 0,
  "bottomTemperature": 0,
  "bottomSalinity": 0,
  "stations": [
    {
      "stationId": 0,
      "coordinate": {
        "lat": 0,
        "lon": 0
      },
      "cvNumber": 0,
      "positionQc": "string",
      "dateQc": "string",
      "comment": "string",
      "type": "string",
      "direction": "string",
      "date": "2025-08-18T11:54:25.402Z",
      "pmax": 0,
      "eol": "2025-08-18T11:54:25.402Z",
      "surface": "2025-08-18T11:54:25.402Z",
      "level": 0,
      "primary": "true",
      "syntheticSampling": "true",
      "physicalParameters": [
        0
      ]
    }
  ],
  "stationsId": [
    0
  ],
  "basins": [
    "string"
  ],
  "parameters": [
    "string"
  ],
  "networkCodes": [
    "string"
  ],
  "groupCodes": [
    "string"
  ],
  "deploymentDate": "2025-08-18T11:54:25.402Z",
  "deploymentYear": "string",
  "countryLabel": "string",
  "institutionLabel": "string",
  "telecomCode": "string",
  "dacCode": "string",
  "platformTypeCode": "string",
  "getpI": "string",
  "cruiseCode": "string",
  "statusCode": "string",
  "sensors": [
    "string"
  ],
  "dataMode": "string",
  "lastUpdateDate": "2025-08-18T11:54:25.402Z",
  "level": 0,
  "physicalParameters": [
    {
      "code": 0,
      "labelWithCode": "string"
    }
  ]
}

# Step 2: Fetch JSON from the API (replace with the right endpoint)
url = "https://dataselection.euro-argo.eu/api/find-by-id/760094"   # <-- update endpoint
response = requests.get(url)
data = response.json()

# Step 3: Validate the JSON response against the schema
try:
    validate(instance=data, schema=schema)
    print("✅ JSON conforms to schema")
except ValidationError as e:
    print("❌ JSON validation error:", e.message)

✅ JSON conforms to schema

In [ ]:
# Basin-tree metadata schema (from api documentation)
schema = {
    "id": 0,
    "name": "string",
    "subBasins": [
      "string"
    ],
    "extent": {
      "coordinates": [
        {
          "coordinates": [
            {
              "type": "string",
              "coordinates": [
                {
                  "x": 0,
                  "y": 0
                }
              ]
            }
          ],
          "type": "string"
        }
      ],
      "type": "string"
    }
  }

# Step 2: Fetch JSON from the API (replace with the right endpoint)
url = "https://dataselection.euro-argo.eu/api/basins-tree"   # <-- update endpoint
response = requests.get(url)
data = response.json()

# Step 3: Validate the JSON response against the schema
try:
    validate(instance=data, schema=schema)
    print("✅ JSON conforms to schema")
except ValidationError as e:
    print("❌ JSON validation error:", e.message)

✅ JSON conforms to schema

#### Interface consistency
*Involves checking naming conventions, field types and data formats, error messages, cross-platform support (language neutral data representation, no additional data transformations needed when consuming the data)*

In [ ]:
import requests
import json

def get_openapi_spec(base_url):
    for path in ["/v2/api-docs", "/v3/api-docs", "/openapi.json", "/swagger.json"]:
        url = base_url.rstrip("/") + path
        r = requests.get(url)
        if r.ok and "json" in r.headers.get("content-type", ""):
            return r.json()
    return None

# Example: Euro-Argo Fleet Monitoring API
spec = get_openapi_spec(base)
print(json.dumps(spec, indent=2))

endpoint = "/api/platforms"   # choose the endpoint you want to inspect
if spec and endpoint in spec["paths"]:
    details = spec["paths"][endpoint]
    print(json.dumps(details, indent=2))
else:
    print(f"Endpoint {endpoint} not found in spec")

{'openapi': '3.0.1', 'info': {'title': 'EADS APi', 'description': 'EADS APi', 'version': '0.1.16'}, 'servers': [{'url': 'https://dataselection.euro-argo.eu', 'description': 'Generated server url'}], 'paths': {'/api/maintenance': {'get': {'tags': ['maintenance-controller'], 'operationId': 'clearMaintenance', 'parameters': [{'name': 'api-key', 'in': 'header', 'required': True, 'schema': {'type': 'string'}}], 'responses': {'200': {'description': 'OK'}}}, 'post': {'tags': ['maintenance-controller'], 'operationId': 'setMaintenance', 'parameters': [{'name': 'api-key', 'in': 'header', 'required': True, 'schema': {'type': 'string'}}], 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/MaintenanceDto'}}}, 'required': True}, 'responses': {'200': {'description': 'OK'}}}}, '/api/full-search-response': {'post': {'tags': ['search-controller'], 'summary': 'Get Cycles cluster groups, total count and facet criteria list for a searchEntry', 'operationId': 'getSearchResponse', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'$ref': '#/components/schemas/SearchResponse'}}}}}}}, '/api/find-by-search': {'post': {'tags': ['cycle-controller'], 'summary': 'Get cycles metadata for a bboxParam', 'operationId': 'getCyclesBySearch', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/EsCycle'}}}}}}}}, '/api/find-by-search-filtred': {'post': {'tags': ['cycle-controller'], 'summary': 'Get cycles metadata for a bboxParam', 'operationId': 'getCyclesBySearchFiltred', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/EsCycle'}}}}}}}}, '/api/export': {'post': {'tags': ['export-controller'], 'summary': 'Send exportRequest', 'operationId': 'sendContactRequest', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/EadsExportRequest'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'boolean'}}}}}}}, '/api/export/parameters': {'post': {'tags': ['export-controller'], 'summary': 'get export parameters', 'operationId': 'getParameters', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'$ref': '#/components/schemas/ExportAvailableDto'}}}}}}}, '/api/criteria-list': {'post': {'tags': ['search-controller'], 'summary': 'Get full criteria list', 'operationId': 'getCriteriaList', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'$ref': '#/components/schemas/SearchResponse'}}}}}}}, '/api/contact/send': {'post': {'tags': ['contact-controller'], 'summary': 'Send mail to support', 'operationId': 'sendContactMail', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ContactMail'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'boolean'}}}}}}}, '/api/analyse/stations/{code}': {'post': {'tags': ['data-view-controller'], 'summary': 'Get phycical parameters used for a search entry', 'operationId': 'getStationIds', 'parameters': [{'name': 'code', 'in': 'path', 'required': True, 'schema': {'type': 'integer', 'format': 'int32'}}], 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'array', 'items': {'type': 'integer', 'format': 'int64'}}}}}}}}, '/api/analyse/physicals': {'post': {'tags': ['data-view-controller'], 'summary': 'Get phycical parameters used for a search entry', 'operationId': 'getPhysicalParameters', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SearchEntry'}}}, 'required': True}, 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/DataView'}}}}}}}}, '/api/trajectory/{platformId}': {'get': {'tags': ['cycle-controller'], 'summary': 'Get a cycle trajectory by platformId', 'operationId': 'getCyclesByPlatformCode', 'parameters': [{'name': 'platformId', 'in': 'path', 'required': True, 'schema': {'type': 'string'}}], 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/EsCycle'}}}}}}}}, '/api/get-version': {'get': {'tags': ['version-controller'], 'summary': 'Get server version', 'operationId': 'getBasicFloats', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}}, '/api/find': {'get': {'tags': ['export-controller'], 'operationId': 'getExportById', 'parameters': [{'name': 'api-key', 'in': 'header', 'required': True, 'schema': {'type': 'string'}}, {'name': 'id', 'in': 'query', 'required': True, 'schema': {'type': 'integer', 'format': 'int64'}}], 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}}, '/api/find-by-platformid/{platformId}/cvnumber/{cvNumber}': {'get': {'tags': ['cycle-controller'], 'summary': 'Get a cycle metadata by platformId and cvNumber', 'operationId': 'getCyclesByPlatformCodeAndCvNumber', 'parameters': [{'name': 'platformId', 'in': 'path', 'required': True, 'schema': {'type': 'string'}}, {'name': 'cvNumber', 'in': 'path', 'required': True, 'schema': {'type': 'integer', 'format': 'int32'}}], 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'$ref': '#/components/schemas/EsCycle'}}}}}}}, '/api/find-by-id/{cycleId}': {'get': {'tags': ['cycle-controller'], 'summary': 'Get a cycle metadata by cycleId', 'operationId': 'getCycleById', 'parameters': [{'name': 'cycleId', 'in': 'path', 'required': True, 'schema': {'type': 'string'}}], 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'$ref': '#/components/schemas/EsCycle'}}}}}}}, '/api/clearAllCaches': {'get': {'tags': ['caching-controller'], 'operationId': 'clearAllCaches', 'parameters': [{'name': 'api-key', 'in': 'header', 'required': True, 'schema': {'type': 'string'}}], 'responses': {'200': {'description': 'OK'}}}}, '/api/basins-tree': {'get': {'tags': ['basin-controller'], 'summary': 'Returns basins names as a tree', 'operationId': 'getbasinsList', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/BasinDto'}}}}}}}}, '/error': {'get': {'tags': ['not-found-controller'], 'operationId': 'handleError', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}, 'put': {'tags': ['not-found-controller'], 'operationId': 'handleError_3', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}, 'post': {'tags': ['not-found-controller'], 'operationId': 'handleError_2', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}, 'delete': {'tags': ['not-found-controller'], 'operationId': 'handleError_5', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}, 'options': {'tags': ['not-found-controller'], 'operationId': 'handleError_6', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}, 'head': {'tags': ['not-found-controller'], 'operationId': 'handleError_1', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}, 'patch': {'tags': ['not-found-controller'], 'operationId': 'handleError_4', 'responses': {'200': {'description': 'OK', 'content': {'*/*': {'schema': {'type': 'string'}}}}}}}}, 'components': {'schemas': {'MaintenanceDto': {'type': 'object', 'properties': {'email': {'type': 'string'}, 'title': {'type': 'string'}, 'message': {'type': 'string'}}}, 'BboxParams': {'required': ['field', 'latBottomRight', 'latTopLeft', 'lonBottomRight', 'lonTopLeft', 'zoom'], 'type': 'object', 'properties': {'field': {'type': 'string'}, 'lonTopLeft': {'maximum': 180, 'minimum': -180, 'type': 'number', 'format': 'double'}, 'latTopLeft': {'maximum': 90, 'minimum': -90, 'type': 'number', 'format': 'double'}, 'lonBottomRight': {'maximum': 180, 'minimum': -180, 'type': 'number', 'format': 'double'}, 'latBottomRight': {'maximum': 90, 'minimum': -90, 'type': 'number', 'format': 'double'}, 'zoom': {'type': 'integer', 'format': 'int32'}}}, 'CriteriaEntry': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'field': {'type': 'string'}, 'values': {'type': 'array', 'items': {'$ref': '#/components/schemas/Criterion'}}, 'types': {'type': 'array', 'items': {'type': 'string', 'enum': ['AUTOCOMPLETE', 'FACET', 'GEOGRAPHIC', 'DATE', 'EVERYWHERE', 'BASIN', 'FREESEARCH', 'FREESEARCH_WITHOUTWILDCARD', 'FREESEARCHFULLTEXT', 'CURSOR', 'BBOX', 'QUERY_STRING', 'SORT_ONLY', 'DATE_RANGE_BAR', 'DATE_RANGE_YEAR_BAR', 'EXPERTSEARCH_LIGHT', 'HIDDEN']}}, 'options': {'type': 'array', 'items': {'type': 'string', 'enum': ['SORTED_VALTXT_DESC', 'SORTED_VALTXT_ASC', 'SORTED_DISABELD', 'TRANSLATED', 'NESTED', 'DEFAULT', 'SORTED_RESULTS', 'HIGHLIGHT_RESULTS', 'RANGE_DATE_NESTED_OBJECT', 'SORTABLE_FIELD']}}, 'order': {'type': 'string', 'enum': ['ASC', 'DESC']}, 'javaClass': {'type': 'string'}, 'facetOrder': {'type': 'integer', 'format': 'int32'}, 'sortPriority': {'type': 'integer', 'format': 'int32'}, 'maxCursorValue': {'type': 'integer', 'format': 'int32'}, 'cursorUnit': {'type': 'string'}, 'coeff': {'type': 'integer', 'format': 'int32'}, 'pattern': {'type': 'string'}, 'defaultFacets': {'type': 'array', 'items': {'$ref': '#/components/schemas/Criterion'}}, 'defaultValues': {'type': 'array', 'items': {'$ref': '#/components/schemas/Criterion'}}, 'referencedFields': {'type': 'array', 'items': {'type': 'string'}}, 'childCriterias': {'type': 'array', 'items': {'$ref': '#/components/schemas/CriteriaEntry'}}, 'weight': {'type': 'number', 'format': 'float'}, 'scoringFunctions': {'type': 'array', 'items': {'$ref': '#/components/schemas/ScoringFunctionEntry'}}, 'searchOrder': {'type': 'integer', 'format': 'int32'}, 'shouldBehaviourCriteria': {'type': 'boolean'}}}, 'Criterion': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'code': {'type': 'string'}, 'n': {'type': 'integer', 'format': 'int64'}}}, 'Pagination': {'required': ['page', 'size'], 'type': 'object', 'properties': {'page': {'type': 'integer', 'format': 'int32'}, 'size': {'type': 'integer', 'format': 'int32'}, 'paginated': {'type': 'boolean'}, 'isPaginated': {'type': 'boolean', 'writeOnly': True}}}, 'ScoringFunctionEntry': {'type': 'object', 'properties': {'field': {'type': 'string'}, 'gte': {'type': 'string'}, 'lte': {'type': 'string'}, 'weight': {'type': 'number', 'format': 'float'}}}, 'SearchEntry': {'required': ['criteriaList'], 'type': 'object', 'properties': {'criteriaList': {'type': 'array', 'items': {'$ref': '#/components/schemas/CriteriaEntry'}}, 'pagination': {'$ref': '#/components/schemas/Pagination'}, 'languageEnum': {'type': 'string', 'enum': ['fr', 'en']}, 'bboxParams': {'$ref': '#/components/schemas/BboxParams'}, 'portal': {'type': 'string'}}}, 'ClusterGroupEsCycle': {'type': 'object', 'properties': {'position': {'type': 'string'}, 'count': {'type': 'integer', 'format': 'int64'}, 'content': {'$ref': '#/components/schemas/EsCycle'}}}, 'EsCycle': {'type': 'object', 'properties': {'highlightFields': {'type': 'object', 'additionalProperties': {'type': 'array', 'items': {'type': 'string'}}}, 'id': {'type': 'integer', 'format': 'int64'}, 'cvNumber': {'type': 'integer', 'format': 'int64'}, 'startDate': {'type': 'string', 'format': 'date-time'}, 'endDate': {'type': 'string', 'format': 'date-time'}, 'coordinate': {'$ref': '#/components/schemas/GeoPoint'}, 'globalGeoShapeField': {'$ref': '#/components/schemas/GeoJsonObject'}, 'platformCode': {'type': 'string'}, 'positionQc': {'type': 'string'}, 'dateQc': {'type': 'string'}, 'cycleQcState': {'type': 'string'}, 'grounded': {'type': 'boolean'}, 'pmax': {'type': 'number', 'format': 'double'}, 'surfacePressure': {'type': 'number', 'format': 'double'}, 'surfaceTemperature': {'type': 'number', 'format': 'double'}, 'surfaceSalinity': {'type': 'number', 'format': 'double'}, 'bottomPressure': {'type': 'number', 'format': 'double'}, 'bottomTemperature': {'type': 'number', 'format': 'double'}, 'bottomSalinity': {'type': 'number', 'format': 'double'}, 'stations': {'uniqueItems': True, 'type': 'array', 'items': {'$ref': '#/components/schemas/EsStation'}}, 'stationsId': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'integer', 'format': 'int64'}}, 'basins': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'string'}}, 'parameters': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'string'}}, 'networkCodes': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'string'}}, 'groupCodes': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'string'}}, 'deploymentDate': {'type': 'string', 'format': 'date-time'}, 'deploymentYear': {'type': 'string'}, 'countryLabel': {'type': 'string'}, 'institutionLabel': {'type': 'string'}, 'telecomCode': {'type': 'string'}, 'dacCode': {'type': 'string'}, 'platformTypeCode': {'type': 'string'}, 'getpI': {'type': 'string'}, 'cruiseCode': {'type': 'string'}, 'statusCode': {'type': 'string'}, 'sensors': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'string'}}, 'dataMode': {'type': 'string'}, 'lastUpdateDate': {'type': 'string', 'format': 'date-time'}, 'level': {'type': 'integer', 'format': 'int32'}, 'physicalParameters': {'uniqueItems': True, 'type': 'array', 'items': {'$ref': '#/components/schemas/EsPhysicalParameter'}}, 'groupCode': {'uniqueItems': True, 'type': 'array', 'writeOnly': True, 'items': {'type': 'string'}}}}, 'EsPhysicalParameter': {'type': 'object', 'properties': {'code': {'type': 'integer', 'format': 'int64'}, 'labelWithCode': {'type': 'string'}}}, 'EsStation': {'type': 'object', 'properties': {'stationId': {'type': 'integer', 'format': 'int64'}, 'coordinate': {'$ref': '#/components/schemas/GeoPoint'}, 'cvNumber': {'type': 'integer', 'format': 'int64'}, 'positionQc': {'type': 'string'}, 'dateQc': {'type': 'string'}, 'comment': {'type': 'string'}, 'type': {'type': 'string'}, 'direction': {'type': 'string'}, 'date': {'type': 'string', 'format': 'date-time'}, 'pmax': {'type': 'number', 'format': 'double'}, 'eol': {'type': 'string', 'format': 'date-time'}, 'surface': {'type': 'string', 'format': 'date-time'}, 'level': {'type': 'integer', 'format': 'int32'}, 'primary': {'type': 'boolean'}, 'syntheticSampling': {'type': 'boolean'}, 'physicalParameters': {'uniqueItems': True, 'type': 'array', 'items': {'type': 'integer', 'format': 'int64'}}}}, 'GeoJsonObject': {'type': 'object', 'properties': {'type': {'type': 'string'}, 'coordinates': {'type': 'object'}}}, 'GeoPoint': {'type': 'object', 'properties': {'lat': {'type': 'number', 'format': 'double'}, 'lon': {'type': 'number', 'format': 'double'}}}, 'SearchResponse': {'type': 'object', 'properties': {'criteriaList': {'type': 'array', 'items': {'$ref': '#/components/schemas/CriteriaEntry'}}, 'responseEntries': {'type': 'array', 'items': {'$ref': '#/components/schemas/EsCycle'}}, 'entriesCount': {'type': 'integer', 'format': 'int64'}, 'pagination': {'$ref': '#/components/schemas/Pagination'}, 'maxClustering': {'type': 'integer', 'format': 'int64'}, 'countClustering': {'type': 'integer', 'format': 'int64'}, 'clusterGroups': {'type': 'array', 'items': {'$ref': '#/components/schemas/ClusterGroupEsCycle'}}}}, 'EadsExportRequest': {'required': ['captchaId', 'exportType'], 'type': 'object', 'properties': {'exportType': {'type': 'string', 'enum': ['CSV', 'NETCDF', 'NETCDF_ORIGINAL']}, 'parameters': {'type': 'array', 'items': {'$ref': '#/components/schemas/CriteriaEntry'}}, 'userMail': {'type': 'string'}, 'captchaResponse': {'maxLength': 6, 'minLength': 4, 'type': 'string'}, 'captchaId': {'type': 'string'}, 'searchEntry': {'$ref': '#/components/schemas/SearchEntry'}}}, 'ExportAvailableDto': {'type': 'object', 'properties': {'qualities': {'type': 'array', 'items': {'$ref': '#/components/schemas/Criterion'}}, 'dataModes': {'type': 'array', 'items': {'$ref': '#/components/schemas/Criterion'}}, 'parameters': {'type': 'array', 'items': {'$ref': '#/components/schemas/Criterion'}}}}, 'ContactMail': {'required': ['captchaId', 'message', 'name', 'subject'], 'type': 'object', 'properties': {'email': {'type': 'string'}, 'name': {'type': 'string'}, 'subject': {'type': 'string'}, 'message': {'type': 'string'}, 'captchaResponse': {'maxLength': 6, 'minLength': 4, 'type': 'string'}, 'captchaId': {'type': 'string'}}}, 'DataView': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'code': {'type': 'string'}, 'n': {'type': 'integer', 'format': 'int64'}}}, 'BasinDto': {'type': 'object', 'properties': {'id': {'type': 'integer', 'format': 'int32'}, 'name': {'type': 'string'}, 'subBasins': {'type': 'array', 'items': {'$ref': '#/components/schemas/BasinDto'}}, 'extent': {'$ref': '#/components/schemas/GeoJsonMultiPolygon'}}}, 'GeoJsonLineString': {'type': 'object', 'properties': {'type': {'type': 'string'}, 'coordinates': {'type': 'array', 'items': {'$ref': '#/components/schemas/Point'}}}}, 'GeoJsonMultiPolygon': {'type': 'object', 'properties': {'coordinates': {'type': 'array', 'items': {'$ref': '#/components/schemas/GeoJsonPolygon'}}, 'type': {'type': 'string'}}}, 'GeoJsonPolygon': {'type': 'object', 'properties': {'coordinates': {'type': 'array', 'items': {'$ref': '#/components/schemas/GeoJsonLineString'}}, 'type': {'type': 'string'}}}, 'Point': {'type': 'object', 'properties': {'x': {'type': 'number', 'format': 'double'}, 'y': {'type': 'number', 'format': 'double'}}}}}}
Endpoint /api/platforms not found in spec

#### Versioning & Backward compatibility
*Involves checking whether the API has a clear versioning strategy and maintains support for older clients when changes to the schema occur*

In [5]:
import requests

# Try typical OpenAPI/Swagger spec URLs
urls = [
    "https://dataselection.euro-argo.eu/v3/api-docs",
    "https://dataselection.euro-argo.eu/v2/api-docs",
    "https://dataselection.euro-argo.eu/openapi.json",
]

for url in urls:
    try:
        r = requests.get(url, timeout=10)
        if r.ok and r.headers.get("content-type", "").startswith("application/json"):
            data = r.json()
            version = data.get("info", {}).get("version")
            print(f"{url} --> version: {version}")
    except Exception as e:
        print(f"{url} --> failed ({e})")

https://dataselection.euro-argo.eu/v3/api-docs --> version: 0.1.16

Findings:

**Standards compliance**  
Fidnings on compliance to HTTP protocol:
- compliant to HTTP protocol
- only correct endpoints listed in swagger api documentation results in valid json response
- other endpoints, either without specified input parameters or with invalid input parameters, do not return the correct application/json content-type ~ improvements could be made
- JSON schemas are defined and available through the documentation and responses from tested endpoints adhere to schemas ~ conformance to JSON schema 

Sidenote: 
- not a RESTful api ~ base endpoints, none existing endpoints return wrong content-type in header

**Interface consistency**  
- use of camelCase naming convention
- no correct error message for wrongly formatted endpoints 


**Versioning & Backward compatibility**  
backward compatibility between api version is an important aspect of technical interoperability.
However, since we have only access to the latest version (V3) and other versions return a 404, we cannot verify this.


Overall, the data is findable, machine accessible and, given knowledge on API structure (which is available through the Swagger API documentation), easily navigatable/usable.

### Semantic Interoperability

#### Documentation
*Involves checking availablity and content of swagger documentation (e.g. definitions include descriptions not just types)*

API documentation available at https://dataselection.euro-argo.eu/swagger-ui/index.html  


The Swagger API documentation clearly lists the available endpoints for a specific HTTP method.  
The listed endpoints can be dynamically explored and tested (with or without input parameters).  

The schemas definitions only include datatypes. Descriptions are not given, making the the meaning of definitions ambiguous to non-domain experts.  

![example-schema-definition](./images/EuroArgo_JsonAPI_exampleschemadefinition.png)

Also in the dynamical exploration of the endpoints, the definitions of input parameters are not given, nor any example values (this is understandable in post requests not in get requests); only datatypes are given.  
Some endpoints require knowledge on wmo-codes, platform-codes, ...

![example-input-parameters](./images/EuroArgo_JsonAPI_exampleinputparameters.png)

#### Metadata 
*Involves checking use of self-describing/unambiguous terms, measurements of units defined, ...*

Example response body of get request for a cycle trajectory by platformId indicates:

- Terms appear to be self-describing (e.g. `lat` and `lon` ~ latitude and longitude),  
however due to lack descriptions in the schema definitions, terms are still ambiguous (e.g. `cycleQcState` -> the quality control state of a cycle; but what is a cycle?) 

- Measurements of units are not defined  
(e.g. surfacePressure, surfaceTemperature, surfaceSalinity values are represented by integer, the unit of measurement is not captured here, nor in antoher key in the response body)  

![example-response-body](./images/EuroArgo_JsonAPI_exampleresponsebody.png)

#### Shared Vocabulary & Ontologies
*Involves checking use of terms from standard vocabularies (ISO, schema.org, ...) and, if applicable, alignment with domain ontologies*

- Dates formats are following ISO 8601 standard.

- Limited/no explicit adherence to other standards (like schema.org, DCAT) or domain standards. This is not mentioned in documentation.   
(though this is not an API that returns JSON-LD, part of used terms do seems to align with terms from schema.org).  

- Limited / no use of persistent identifiers (URIs) - e.g. wmo-codes/platform-codes, types, ... could be represented by URLs from existing standards.

#### Contextual Meaning
*Involves checking context terms (e.g. `"status":"active"`) and enumerations are clearly defined so their meaning is consistent across different systems*

- no notes

**Note on data granularity**

to include!